import mongoose from 'mongoose'
import dotenv from 'dotenv'
import path from 'path'
import { fileURLToPath } from 'url'
import CbtQuestion from '../src/models/CbtQuestion.js'

const __filename = fileURLToPath(import.meta.url)
const __dirname = path.dirname(__filename)

dotenv.config({ path: path.join(__dirname, '../.env') })

const questionsData = [
  // ==================== BIOLOGY — SET A ====================
  // NUTRITION (Subsection 1)
  {
    subject: 'Biology',
    subsection_id: 1,
    subsection_name: 'Nutrition',
    question_set: 'Set A',
    question_text: 'Which adaptation of the small intestine allows digested food to be absorbed efficiently?',
    options: {
      A: 'Thick walls and few blood vessels',
      B: 'Large surface area and a good blood supply',
      C: 'Small surface area and thick epithelium',
      D: 'Absence of blood capillaries',
    },
    correct_option: 'B',
    explanation: 'A large surface area created by villi and microvilli along with a dense capillary network allows efficient absorption.',
  },
  {
    subject: 'Biology',
    subsection_id: 1,
    subsection_name: 'Nutrition',
    question_set: 'Set A',
    question_text: 'Which of the following nutrients is absorbed into the lacteals of the villi?',
    options: {
      A: 'Glucose',
      B: 'Amino acids',
      C: 'Fatty acids and glycerol',
      D: 'Mineral salts',
    },
    correct_option: 'C',
    explanation: 'Fatty acids and glycerol are processed into chylomicrons and absorbed into the lymphatic lacteals.',
  },
  {
    subject: 'Biology',
    subsection_id: 1,
    subsection_name: 'Nutrition',
    question_set: 'Set A',
    question_text: 'A person who does not get enough vitamin C in their diet is likely to develop:',
    options: {
      A: 'Rickets',
      B: 'Scurvy',
      C: 'Beriberi',
      D: 'Goitre',
    },
    correct_option: 'B',
    explanation: 'Vitamin C deficiency impairs collagen synthesis, causing scurvy characterized by bleeding gums.',
  },
  {
    subject: 'Biology',
    subsection_id: 1,
    subsection_name: 'Nutrition',
    question_set: 'Set A',
    question_text: 'Which disease is commonly associated with severe protein deficiency in children?',
    options: {
      A: 'Kwashiorkor',
      B: 'Scurvy',
      C: 'Rickets',
      D: 'Goitre',
    },
    correct_option: 'A',
    explanation: 'Kwashiorkor is caused by severe protein deficiency, leading to edema and abdominal swelling.',
  },
  {
    subject: 'Biology',
    subsection_id: 1,
    subsection_name: 'Nutrition',
    question_set: 'Set A',
    question_text: 'Which nutritional deficiency can lead to night blindness?',
    options: {
      A: 'Vitamin A deficiency',
      B: 'Vitamin C deficiency',
      C: 'Iron deficiency',
      D: 'Vitamin D deficiency',
    },
    correct_option: 'A',
    explanation: 'Vitamin A (retinol) is essential for rhodopsin synthesis in rod cells of the retina.',
  },

  // GENETICS (Subsection 2)
  {
    subject: 'Biology',
    subsection_id: 2,
    subsection_name: 'Genetics',
    question_set: 'Set A',
    question_text: 'Which structure carries the genetic information that determines the characteristics of an organism?',
    options: {
      A: 'Ribosome',
      B: 'DNA',
      C: 'Cell membrane',
      D: 'Cytoplasm',
    },
    correct_option: 'B',
    explanation: 'DNA holds genetic instructions encoding functional proteins and traits.',
  },
  {
    subject: 'Biology',
    subsection_id: 2,
    subsection_name: 'Genetics',
    question_set: 'Set A',
    question_text: 'A plant with genotype Tt is crossed with another plant with genotype Tt. What proportion of their offspring is expected to have the genotype tt?',
    options: {
      A: '0%',
      B: '25%',
      C: '50%',
      D: '75%',
    },
    correct_option: 'B',
    explanation: 'Crossing Tt x Tt yields genotypes TT (25%), Tt (50%), and tt (25%).',
  },
  {
    subject: 'Biology',
    subsection_id: 2,
    subsection_name: 'Genetics',
    question_set: 'Set A',
    question_text: 'Which statement correctly describes an allele?',
    options: {
      A: 'A type of cell division',
      B: 'An alternative form of a gene',
      C: 'A complete set of chromosomes',
      D: 'A section of the cell membrane',
    },
    correct_option: 'B',
    explanation: 'An allele is a specific variant form of a gene located at a specific genetic locus.',
  },
  {
    subject: 'Biology',
    subsection_id: 2,
    subsection_name: 'Genetics',
    question_set: 'Set A',
    question_text: 'In a species, brown eyes are dominant to blue eyes. If two heterozygous brown-eyed individuals have a child, what is the probability that the child will have blue eyes?',
    options: {
      A: '0%',
      B: '25%',
      C: '50%',
      D: '75%',
    },
    correct_option: 'B',
    explanation: 'Bb x Bb cross produces 1/4 (25%) recessive bb (blue eyes).',
  },
  {
    subject: 'Biology',
    subsection_id: 2,
    subsection_name: 'Genetics',
    question_set: 'Set A',
    question_text: 'Which process produces gametes with half the normal chromosome number?',
    options: {
      A: 'Mitosis',
      B: 'Fertilisation',
      C: 'Meiosis',
      D: 'Binary fission',
    },
    correct_option: 'C',
    explanation: 'Meiosis is a reductional cell division forming haploid gametes.',
  },

  // ECOLOGY (Subsection 3)
  {
    subject: 'Biology',
    subsection_id: 3,
    subsection_name: 'Ecology',
    question_set: 'Set A',
    question_text: 'Which of the following best describes a population?',
    options: {
      A: 'All organisms living in an ecosystem',
      B: 'All organisms of the same species living in a particular area',
      C: 'All plants living in a particular habitat',
      D: 'All animals living in a community',
    },
    correct_option: 'B',
    explanation: 'A population consists of individuals of the same species co-existing in a defined geographic area.',
  },
  {
    subject: 'Biology',
    subsection_id: 3,
    subsection_name: 'Ecology',
    question_set: 'Set A',
    question_text: 'Why are green plants important as producers in an ecosystem?',
    options: {
      A: 'They obtain energy by feeding on animals',
      B: 'They convert light energy into chemical energy during photosynthesis',
      C: 'They decompose dead organisms',
      D: 'They obtain organic nutrients directly from the soil',
    },
    correct_option: 'B',
    explanation: 'Producers fix solar radiation into organic chemical energy via photosynthesis.',
  },
  {
    subject: 'Biology',
    subsection_id: 3,
    subsection_name: 'Ecology',
    question_set: 'Set A',
    question_text: 'In a food chain, the amount of energy available generally decreases at each successive trophic level. Which factor mainly accounts for this?',
    options: {
      A: 'All organisms are the same size',
      B: 'Energy is lost through processes such as respiration and heat production',
      C: 'Producers consume most of the available energy',
      D: 'Consumers do not require energy for movement',
    },
    correct_option: 'B',
    explanation: 'Metabolic heat loss and unconsumed biomass limit trophic energy transfer efficiency to ~10%.',
  },
  {
    subject: 'Biology',
    subsection_id: 3,
    subsection_name: 'Ecology',
    question_set: 'Set A',
    question_text: 'Which plant adaptation would be most useful to a plant growing in a dry habitat?',
    options: {
      A: 'Large leaves with many stomata',
      B: 'Thin cuticle and shallow roots',
      C: 'Reduced leaf area and a thick waxy cuticle',
      D: 'Broad leaves with a thin epidermis',
    },
    correct_option: 'C',
    explanation: 'Xerophytic adaptations like reduced leaf surface area and thick cuticles minimize transpiration water loss.',
  },
  {
    subject: 'Biology',
    subsection_id: 3,
    subsection_name: 'Ecology',
    question_set: 'Set A',
    question_text: 'A population of rabbits in a grassland initially increases rapidly but later becomes relatively stable. What is the most likely reason for the slowing of population growth?',
    options: {
      A: 'Unlimited food supply',
      B: 'Increased availability of habitats',
      C: 'Increased competition for limited resources',
      D: 'Decreased competition between individuals',
    },
    correct_option: 'C',
    explanation: 'Intraspecific competition for food and space reaches ecological carrying capacity.',
  },

  // ANIMAL BIOLOGY (Subsection 4)
  {
    subject: 'Biology',
    subsection_id: 4,
    subsection_name: 'Animal Biology',
    question_set: 'Set A',
    question_text: "Which feature of an insect's respiratory system allows oxygen to reach body tissues without being transported by the blood?",
    options: {
      A: 'Haemoglobin in the blood',
      B: 'A network of tracheal tubes',
      C: 'Numerous red blood cells',
      D: 'A closed circulatory system',
    },
    correct_option: 'B',
    explanation: 'Insects deliver oxygen directly to tissues via branching tracheae opening through spiracles.',
  },
  {
    subject: 'Biology',
    subsection_id: 4,
    subsection_name: 'Animal Biology',
    question_set: 'Set A',
    question_text: 'Which of the following animals has a two-chambered heart?',
    options: {
      A: 'Fish',
      B: 'Frog',
      C: 'Bird',
      D: 'Mammal',
    },
    correct_option: 'A',
    explanation: 'Fish possess a simple single-circuit heart with one atrium and one ventricle.',
  },
  {
    subject: 'Biology',
    subsection_id: 4,
    subsection_name: 'Animal Biology',
    question_set: 'Set A',
    question_text: 'In fish, water flows over the gills in one direction while blood flows through the gill capillaries in the opposite direction. What is the main advantage of this arrangement?',
    options: {
      A: 'It prevents water from entering the bloodstream',
      B: 'It maintains a concentration gradient for oxygen along the entire length of the gill',
      C: 'It allows blood to flow directly from the gills to the body',
      D: 'It reduces the surface area available for gas exchange',
    },
    correct_option: 'B',
    explanation: 'Countercurrent exchange maximizes oxygen extraction efficiency across the respiratory membrane.',
  },
  {
    subject: 'Biology',
    subsection_id: 4,
    subsection_name: 'Animal Biology',
    question_set: 'Set A',
    question_text: 'Which combination correctly matches an animal with its respiratory organ?',
    options: {
      A: 'Earthworm — tracheal system',
      B: 'Fish — lungs',
      C: 'Grasshopper — tracheal system',
      D: 'Frog — gills only',
    },
    correct_option: 'C',
    explanation: 'Grasshoppers are insects that respire via a tracheal system.',
  },
  {
    subject: 'Biology',
    subsection_id: 4,
    subsection_name: 'Animal Biology',
    question_set: 'Set A',
    question_text: 'A frog can exchange gases through both its lungs and its moist skin. What advantage does cutaneous respiration provide?',
    options: {
      A: 'It allows gas exchange when the frog is not actively using its lungs',
      B: 'It completely replaces the need for lungs in adult frogs',
      C: 'It prevents carbon dioxide from leaving the body',
      D: 'It allows oxygen to be transported directly through the bones',
    },
    correct_option: 'A',
    explanation: 'Cutaneous gas exchange supports oxygen uptake during submergence in water or dormancy.',
  },

  // PLANT BIOLOGY (Subsection 5)
  {
    subject: 'Biology',
    subsection_id: 5,
    subsection_name: 'Plant Biology',
    question_set: 'Set A',
    question_text: 'Which plant tissue is mainly responsible for transporting water and mineral ions from the roots to the leaves?',
    options: {
      A: 'Phloem',
      B: 'Xylem',
      C: 'Epidermis',
      D: 'Cambium',
    },
    correct_option: 'B',
    explanation: 'Xylem vessels transport water and dissolved minerals unidirectionally via transpiration pull.',
  },
  {
    subject: 'Biology',
    subsection_id: 5,
    subsection_name: 'Plant Biology',
    question_set: 'Set A',
    question_text: 'Which feature of xylem vessels makes them well suited for transporting water through a plant?',
    options: {
      A: 'They contain many living cells with thin walls',
      B: 'They have end walls that prevent water movement',
      C: 'They form continuous hollow tubes with thick, lignified walls',
      D: 'They contain sieve plates for transporting sugars',
    },
    correct_option: 'C',
    explanation: 'Lignified dead hollow tubes resist collapse under high tension forces.',
  },
  {
    subject: 'Biology',
    subsection_id: 5,
    subsection_name: 'Plant Biology',
    question_set: 'Set A',
    question_text: 'Which tissue provides flexible support to young, growing parts of a plant?',
    options: {
      A: 'Collenchyma',
      B: 'Sclerenchyma',
      C: 'Xylem',
      D: 'Phloem',
    },
    correct_option: 'A',
    explanation: 'Collenchyma cells possess unevenly thickened pectin-rich cell walls providing mechanical elasticity.',
  },
  {
    subject: 'Biology',
    subsection_id: 5,
    subsection_name: 'Plant Biology',
    question_set: 'Set A',
    question_text: 'Sclerenchyma cells provide strong mechanical support mainly because their cell walls:',
    options: {
      A: 'Contain large amounts of cellulose but no other substances',
      B: 'Are thin and flexible',
      C: 'Are thickened with lignin',
      D: 'Contain numerous chloroplasts',
    },
    correct_option: 'C',
    explanation: 'Heavy secondary wall lignification delivers rigid structural support.',
  },
  {
    subject: 'Biology',
    subsection_id: 5,
    subsection_name: 'Plant Biology',
    question_set: 'Set A',
    question_text: 'A young stem bends in strong wind but does not break, while an older woody stem remains rigid. Which combination of tissues is most responsible for these forms of support?',
    options: {
      A: 'Collenchyma in the young stem and sclerenchyma in the older stem',
      B: 'Sclerenchyma in the young stem and epidermis in the older stem',
      C: 'Phloem in the young stem and collenchyma in the older stem',
      D: 'Epidermis in the young stem and phloem in the older stem',
    },
    correct_option: 'A',
    explanation: 'Collenchyma confers flexible compliance while mature sclerenchyma offers rigid strength.',
  },

  // ==================== BIOLOGY — SET B ====================
  // NUTRITION (Subsection 1)
  {
    subject: 'Biology',
    subsection_id: 1,
    subsection_name: 'Nutrition',
    question_set: 'Set B',
    question_text: 'What is the main advantage of having numerous villi in the small intestine?',
    options: {
      A: 'They increase the production of bile',
      B: 'They increase the surface area for absorption',
      C: 'They prevent food from entering the large intestine',
      D: 'They digest proteins in the stomach',
    },
    correct_option: 'B',
    explanation: 'Villi tremendously expand the surface area available for nutrient uptake.',
  },
  {
    subject: 'Biology',
    subsection_id: 1,
    subsection_name: 'Nutrition',
    question_set: 'Set B',
    question_text: 'Which substance is mainly absorbed into the blood capillaries of the villi?',
    options: {
      A: 'Fat droplets',
      B: 'Glucose and amino acids',
      C: 'Bile salts only',
      D: 'Undigested fibre',
    },
    correct_option: 'B',
    explanation: 'Water-soluble monosaccharides and amino acids enter the hepatic portal capillaries directly.',
  },
  {
    subject: 'Biology',
    subsection_id: 1,
    subsection_name: 'Nutrition',
    question_set: 'Set B',
    question_text: 'A child has weak and poorly developed bones due to a deficiency of a particular vitamin. Which vitamin is most likely lacking?',
    options: {
      A: 'Vitamin A',
      B: 'Vitamin B',
      C: 'Vitamin C',
      D: 'Vitamin D',
    },
    correct_option: 'D',
    explanation: 'Vitamin D is crucial for intestinal calcium absorption and bone mineralization (preventing rickets).',
  },
  {
    subject: 'Biology',
    subsection_id: 1,
    subsection_name: 'Nutrition',
    question_set: 'Set B',
    question_text: 'Which disease may result from a lack of sufficient iron in the diet?',
    options: {
      A: 'Anaemia',
      B: 'Rickets',
      C: 'Scurvy',
      D: 'Pellagra',
    },
    correct_option: 'A',
    explanation: 'Iron deficiency impairs hemoglobin synthesis, producing microcytic anemia.',
  },
  {
    subject: 'Biology',
    subsection_id: 1,
    subsection_name: 'Nutrition',
    question_set: 'Set B',
    question_text: 'A person develops an enlarged thyroid gland because their diet lacks an essential mineral. Which mineral is deficient?',
    options: {
      A: 'Calcium',
      B: 'Iron',
      C: 'Iodine',
      D: 'Sodium',
    },
    correct_option: 'C',
    explanation: 'Iodine is a structural component of thyroid hormones T3 and T4; deficiency leads to goitre.',
  },

  // GENETICS (Subsection 2)
  {
    subject: 'Biology',
    subsection_id: 2,
    subsection_name: 'Genetics',
    question_set: 'Set B',
    question_text: 'Which molecule is responsible for carrying genetic information from one generation to the next?',
    options: {
      A: 'ATP',
      B: 'DNA',
      C: 'Glucose',
      D: 'Protein',
    },
    correct_option: 'B',
    explanation: 'Deoxyribonucleic acid (DNA) stores hereditary genomic blueprints.',
  },
  {
    subject: 'Biology',
    subsection_id: 2,
    subsection_name: 'Genetics',
    question_set: 'Set B',
    question_text: 'If B represents a dominant allele and b represents a recessive allele, which genotype is heterozygous?',
    options: {
      A: 'BB',
      B: 'Bb',
      C: 'bb',
      D: 'B',
    },
    correct_option: 'B',
    explanation: 'Heterozygous organisms carry two distinct alleles (Bb).',
  },
  {
    subject: 'Biology',
    subsection_id: 2,
    subsection_name: 'Genetics',
    question_set: 'Set B',
    question_text: 'A tall plant with genotype Tt is crossed with a short plant with genotype tt. What percentage of the offspring is expected to be short?',
    options: {
      A: '0%',
      B: '25%',
      C: '50%',
      D: '100%',
    },
    correct_option: 'C',
    explanation: 'Test cross Tt x tt gives 50% Tt (tall) and 50% tt (short).',
  },
  {
    subject: 'Biology',
    subsection_id: 2,
    subsection_name: 'Genetics',
    question_set: 'Set B',
    question_text: 'Which event during meiosis is an important source of genetic variation?',
    options: {
      A: 'DNA replication',
      B: 'Crossing over between homologous chromosomes',
      C: 'Formation of two daughter cells by mitosis',
      D: 'Production of identical chromosomes',
    },
    correct_option: 'B',
    explanation: 'Homologous recombination (crossing over) in prophase I scrambles maternal and paternal alleles.',
  },
  {
    subject: 'Biology',
    subsection_id: 2,
    subsection_name: 'Genetics',
    question_set: 'Set B',
    question_text: 'A DNA molecule contains 30% adenine. What percentage of the molecule is expected to be cytosine?',
    options: {
      A: '20%',
      B: '30%',
      C: '40%',
      D: '70%',
    },
    correct_option: 'A',
    explanation: "By Chargaff's rule: %A = %T = 30%. Thus %G + %C = 40%, meaning %C = 20%.",
  },

  // ECOLOGY (Subsection 3)
  {
    subject: 'Biology',
    subsection_id: 3,
    subsection_name: 'Ecology',
    question_set: 'Set B',
    question_text: 'Which term describes all the different populations of organisms living and interacting in a particular area?',
    options: {
      A: 'Habitat',
      B: 'Population',
      C: 'Community',
      D: 'Species',
    },
    correct_option: 'C',
    explanation: 'A biological community comprises all co-occurring biotic populations.',
  },
  {
    subject: 'Biology',
    subsection_id: 3,
    subsection_name: 'Ecology',
    question_set: 'Set B',
    question_text: 'Why are decomposers important in an ecosystem?',
    options: {
      A: 'They produce glucose through photosynthesis',
      B: 'They return mineral nutrients to the environment',
      C: 'They increase the amount of sunlight available to plants',
      D: 'They prevent all organisms from competing for resources',
    },
    correct_option: 'B',
    explanation: 'Decomposers recycle organic carbon and inorganic nitrogen/phosphorus minerals back into soil.',
  },
  {
    subject: 'Biology',
    subsection_id: 3,
    subsection_name: 'Ecology',
    question_set: 'Set B',
    question_text: 'Two plant species growing in the same area have roots that absorb mineral ions from the same region of soil. What type of interaction is most likely to occur between the plants?',
    options: {
      A: 'Mutualism',
      B: 'Predation',
      C: 'Competition',
      D: 'Parasitism',
    },
    correct_option: 'C',
    explanation: 'Interspecific competition arises when resources are limited.',
  },
  {
    subject: 'Biology',
    subsection_id: 3,
    subsection_name: 'Ecology',
    question_set: 'Set B',
    question_text: 'A farmer removes most of the vegetation from an area, leaving the soil exposed. Which effect is most likely to occur?',
    options: {
      A: 'Increased soil erosion',
      B: 'Increased photosynthesis',
      C: 'Reduced loss of mineral ions',
      D: 'Increased habitat availability for all organisms',
    },
    correct_option: 'A',
    explanation: 'Vegetation cover anchors topsoil; removing plants accelerates wind/water soil erosion.',
  },
  {
    subject: 'Biology',
    subsection_id: 3,
    subsection_name: 'Ecology',
    question_set: 'Set B',
    question_text: 'In a pond ecosystem, the number of algae increases greatly after fertiliser containing nitrates enters the water. What is the most likely consequence?',
    options: {
      A: 'Increased oxygen concentration caused by decomposition',
      B: 'Reduced decomposition of dead organisms',
      C: 'Decreased oxygen concentration as microorganisms decompose dead algae',
      D: 'Immediate increase in the population of all aquatic animals',
    },
    correct_option: 'C',
    explanation: 'Eutrophication leads to algal blooms; bacterial decay of dead algae depletes dissolved oxygen.',
  },

  // ANIMAL BIOLOGY (Subsection 4)
  {
    subject: 'Biology',
    subsection_id: 4,
    subsection_name: 'Animal Biology',
    question_set: 'Set B',
    question_text: 'In insects, which system is primarily responsible for transporting oxygen directly to body tissues?',
    options: {
      A: 'Circulatory system',
      B: 'Tracheal system',
      C: 'Digestive system',
      D: 'Excretory system',
    },
    correct_option: 'B',
    explanation: 'Tracheae bypass the circulatory fluid to supply oxygen straight to cells.',
  },
  {
    subject: 'Biology',
    subsection_id: 4,
    subsection_name: 'Animal Biology',
    question_set: 'Set B',
    question_text: 'Which structure in a fish is mainly responsible for the removal of nitrogenous waste from the blood?',
    options: {
      A: 'Gills',
      B: 'Kidney',
      C: 'Liver',
      D: 'Intestine',
    },
    correct_option: 'B',
    explanation: 'The mesonephric kidney filters metabolic wastes (ammonia/urea) from blood.',
  },
  {
    subject: 'Biology',
    subsection_id: 4,
    subsection_name: 'Animal Biology',
    question_set: 'Set B',
    question_text: 'In mammals, which part of the nervous system is responsible for carrying impulses from receptors towards the central nervous system?',
    options: {
      A: 'Motor neurones',
      B: 'Sensory neurones',
      C: 'Relay neurones',
      D: 'Effector cells',
    },
    correct_option: 'B',
    explanation: 'Afferent sensory neurons transmit action potentials from peripheral sensory receptors to the CNS.',
  },
  {
    subject: 'Biology',
    subsection_id: 4,
    subsection_name: 'Animal Biology',
    question_set: 'Set B',
    question_text: 'Which hormone helps regulate the water content of the blood by increasing water reabsorption in the kidneys?',
    options: {
      A: 'Insulin',
      B: 'Glucagon',
      C: 'ADH',
      D: 'Adrenaline',
    },
    correct_option: 'C',
    explanation: 'Antidiuretic hormone (ADH) increases aquaporin insertion in renal collecting ducts.',
  },
  {
    subject: 'Biology',
    subsection_id: 4,
    subsection_name: 'Animal Biology',
    question_set: 'Set B',
    question_text: 'An animal has a body divided into segments, a well-developed nervous system, and specialised organs for excretion. Which of the following is most likely to be an annelid?',
    options: {
      A: 'Starfish',
      B: 'Earthworm',
      C: 'Snail',
      D: 'Grasshopper',
    },
    correct_option: 'B',
    explanation: 'Earthworms belong to phylum Annelida, characterized by metameric segmentation.',
  },

  // PLANT BIOLOGY (Subsection 5)
  {
    subject: 'Biology',
    subsection_id: 5,
    subsection_name: 'Plant Biology',
    question_set: 'Set B',
    question_text: 'Which structure in a leaf controls the movement of gases into and out of the leaf?',
    options: {
      A: 'Xylem',
      B: 'Stoma',
      C: 'Phloem',
      D: 'Palisade mesophyll',
    },
    correct_option: 'B',
    explanation: 'Stomata surrounded by guard cells regulate gas diffusion (CO2, O2, H2O).',
  },
  {
    subject: 'Biology',
    subsection_id: 5,
    subsection_name: 'Plant Biology',
    question_set: 'Set B',
    question_text: 'Which tissue is mainly responsible for transporting the products of photosynthesis from leaves to other parts of a plant?',
    options: {
      A: 'Xylem',
      B: 'Epidermis',
      C: 'Phloem',
      D: 'Cambium',
    },
    correct_option: 'C',
    explanation: 'Phloem sieve tube elements conduct sucrose via pressure-flow translocation.',
  },
  {
    subject: 'Biology',
    subsection_id: 5,
    subsection_name: 'Plant Biology',
    question_set: 'Set B',
    question_text: 'Which factor would most directly increase the rate of transpiration from a plant?',
    options: {
      A: 'Increased humidity',
      B: 'Reduced temperature',
      C: 'Increased wind speed',
      D: 'Reduced light intensity',
    },
    correct_option: 'C',
    explanation: 'Wind blows away boundary layer water vapor, sharpening the transpiration concentration gradient.',
  },
  {
    subject: 'Biology',
    subsection_id: 5,
    subsection_name: 'Plant Biology',
    question_set: 'Set B',
    question_text: 'Which structure is characteristic of fungi and consists of long, thread-like filaments?',
    options: {
      A: 'Rhizoid',
      B: 'Hypha',
      C: 'Stoma',
      D: 'Spore',
    },
    correct_option: 'B',
    explanation: 'Hyphae are filamentous fungal structures forming a mycelial network.',
  },
  {
    subject: 'Biology',
    subsection_id: 5,
    subsection_name: 'Plant Biology',
    question_set: 'Set B',
    question_text: 'Which method of reproduction is commonly used by fungi such as Rhizopus?',
    options: {
      A: 'Production of spores',
      B: 'Production of seeds',
      C: 'Binary fission',
      D: 'Formation of flowers',
    },
    correct_option: 'A',
    explanation: 'Rhizopus reproduces via asexual sporangiospores in sporangia.',
  },

  // ==================== MATHEMATICS — SET A ====================
  // GEOMETRY (Subsection 1)
  {
    subject: 'Mathematics',
    subsection_id: 1,
    subsection_name: 'Geometry',
    question_set: 'Set A',
    question_text: 'The angles of a triangle are in the ratio 2 : 3 : 4. What is the largest angle?',
    options: {
      A: '40°',
      B: '60°',
      C: '80°',
      D: '100°',
    },
    correct_option: 'C',
    explanation: 'Sum of parts = 2+3+4 = 9. Largest angle = (4/9) * 180° = 80°.',
  },
  {
    subject: 'Mathematics',
    subsection_id: 1,
    subsection_name: 'Geometry',
    question_set: 'Set A',
    question_text: 'A rectangular field has an area of 240 m². If its length is 20 m, what is its perimeter?',
    options: {
      A: '44 m',
      B: '48 m',
      C: '52 m',
      D: '64 m',
    },
    correct_option: 'D',
    explanation: 'Width = 240 / 20 = 12 m. Perimeter = 2 * (20 + 12) = 64 m.',
  },
  {
    subject: 'Mathematics',
    subsection_id: 1,
    subsection_name: 'Geometry',
    question_set: 'Set A',
    question_text: 'A square has an area of 144 cm². What is the length of its diagonal?',
    options: {
      A: '12 cm',
      B: '18 cm',
      C: '12√2 cm',
      D: '24 cm',
    },
    correct_option: 'C',
    explanation: 'Side length = √144 = 12 cm. Diagonal = side * √2 = 12√2 cm.',
  },
  {
    subject: 'Mathematics',
    subsection_id: 1,
    subsection_name: 'Geometry',
    question_set: 'Set A',
    question_text: 'A right-angled triangle has a hypotenuse of 13 cm and one side of 5 cm. Find the length of the other side.',
    options: {
      A: '8 cm',
      B: '10 cm',
      C: '12 cm',
      D: '14 cm',
    },
    correct_option: 'C',
    explanation: 'Other side = √(13² - 5²) = √(169 - 25) = √144 = 12 cm.',
  },
  {
    subject: 'Mathematics',
    subsection_id: 1,
    subsection_name: 'Geometry',
    question_set: 'Set A',
    question_text: 'The exterior angle of a triangle is 120°. If one of the opposite interior angles is 50°, find the other.',
    options: {
      A: '60°',
      B: '70°',
      C: '80°',
      D: '90°',
    },
    correct_option: 'B',
    explanation: 'Exterior angle = sum of opposite interior angles. 120° = 50° + x => x = 70°.',
  },

  // ALGEBRA (Subsection 2)
  {
    subject: 'Mathematics',
    subsection_id: 2,
    subsection_name: 'Algebra',
    question_set: 'Set A',
    question_text: 'Solve: 3x + 7 = 22',
    options: {
      A: '3',
      B: '4',
      C: '5',
      D: '6',
    },
    correct_option: 'C',
    explanation: '3x = 22 - 7 = 15 => x = 5.',
  },
  {
    subject: 'Mathematics',
    subsection_id: 2,
    subsection_name: 'Algebra',
    question_set: 'Set A',
    question_text: 'Simplify: 3(2x − 5) + 4x',
    options: {
      A: '10x − 15',
      B: '10x − 5',
      C: '6x − 20',
      D: '2x − 15',
    },
    correct_option: 'A',
    explanation: '6x - 15 + 4x = 10x - 15.',
  },
  {
    subject: 'Mathematics',
    subsection_id: 2,
    subsection_name: 'Algebra',
    question_set: 'Set A',
    question_text: 'Factorize: x² + 7x + 12',
    options: {
      A: '(x + 2)(x + 6)',
      B: '(x + 3)(x + 4)',
      C: '(x − 3)(x − 4)',
      D: '(x + 1)(x + 12)',
    },
    correct_option: 'B',
    explanation: 'Numbers multiplying to 12 and adding to 7 are 3 and 4.',
  },
  {
    subject: 'Mathematics',
    subsection_id: 2,
    subsection_name: 'Algebra',
    question_set: 'Set A',
    question_text: 'Solve: 2x − 3 = x + 5',
    options: {
      A: '5',
      B: '6',
      C: '7',
      D: '8',
    },
    correct_option: 'D',
    explanation: '2x - x = 5 + 3 => x = 8.',
  },
  {
    subject: 'Mathematics',
    subsection_id: 2,
    subsection_name: 'Algebra',
    question_set: 'Set A',
    question_text: 'If x = −2, find the value of: x² − 3x + 4',
    options: {
      A: '6',
      B: '10',
      C: '12',
      D: '14',
    },
    correct_option: 'D',
    explanation: '(-2)² - 3(-2) + 4 = 4 + 6 + 4 = 14.',
  },

  // SET THEORY (Subsection 3)
  {
    subject: 'Mathematics',
    subsection_id: 3,
    subsection_name: 'Set Theory',
    question_set: 'Set A',
    question_text: 'If A = {1, 2, 3, 4, 5} and B = {2, 4, 6, 8}, find A ∩ B.',
    options: {
      A: '{1, 3, 5}',
      B: '{2, 4}',
      C: '{2, 4, 6}',
      D: '{1, 2, 3, 4}',
    },
    correct_option: 'B',
    explanation: 'Intersection A ∩ B contains common elements {2, 4}.',
  },
  {
    subject: 'Mathematics',
    subsection_id: 3,
    subsection_name: 'Set Theory',
    question_set: 'Set A',
    question_text: 'In a class of 40 students, 25 study Mathematics, 18 study Physics, and 10 study both. How many students study at least one of the two subjects?',
    options: {
      A: '30',
      B: '33',
      C: '35',
      D: '43',
    },
    correct_option: 'B',
    explanation: 'n(M ∪ P) = n(M) + n(P) - n(M ∩ P) = 25 + 18 - 10 = 33.',
  },
  {
    subject: 'Mathematics',
    subsection_id: 3,
    subsection_name: 'Set Theory',
    question_set: 'Set A',
    question_text: 'Using the information in the previous question (40 total, 33 study at least one), how many students study neither Mathematics nor Physics?',
    options: {
      A: '5',
      B: '7',
      C: '10',
      D: '12',
    },
    correct_option: 'B',
    explanation: 'Neither = Total - n(M ∪ P) = 40 - 33 = 7.',
  },
  {
    subject: 'Mathematics',
    subsection_id: 3,
    subsection_name: 'Set Theory',
    question_set: 'Set A',
    question_text: 'If n(A) = 18, n(B) = 25 and n(A ∪ B) = 35, find n(A ∩ B).',
    options: {
      A: '5',
      B: '8',
      C: '10',
      D: '12',
    },
    correct_option: 'B',
    explanation: 'n(A ∩ B) = n(A) + n(B) - n(A ∪ B) = 18 + 25 - 35 = 8.',
  },
  {
    subject: 'Mathematics',
    subsection_id: 3,
    subsection_name: 'Set Theory',
    question_set: 'Set A',
    question_text: 'If a set contains 5 elements, how many subsets does it have?',
    options: {
      A: '10',
      B: '16',
      C: '25',
      D: '32',
    },
    correct_option: 'D',
    explanation: 'Number of subsets = 2^n = 2^5 = 32.',
  },

  // TRIGONOMETRY (Subsection 4)
  {
    subject: 'Mathematics',
    subsection_id: 4,
    subsection_name: 'Trigonometry',
    question_set: 'Set A',
    question_text: 'If sin θ = 3/5 and θ is acute, find cos θ.',
    options: {
      A: '2/5',
      B: '3/4',
      C: '4/5',
      D: '5/4',
    },
    correct_option: 'C',
    explanation: 'cos θ = √(1 - sin²θ) = √(1 - 9/25) = √(16/25) = 4/5.',
  },
  {
    subject: 'Mathematics',
    subsection_id: 4,
    subsection_name: 'Trigonometry',
    question_set: 'Set A',
    question_text: 'If tan θ = 3/4, find sin θ.',
    options: {
      A: '3/5',
      B: '4/5',
      C: '3/4',
      D: '4/3',
    },
    correct_option: 'A',
    explanation: 'Opposite=3, Adjacent=4 => Hypotenuse=5. sin θ = 3/5.',
  },
  {
    subject: 'Mathematics',
    subsection_id: 4,
    subsection_name: 'Trigonometry',
    question_set: 'Set A',
    question_text: 'Evaluate: sin 30° + cos 60°',
    options: {
      A: '0',
      B: '1/2',
      C: '1',
      D: '2',
    },
    correct_option: 'C',
    explanation: 'sin 30° = 1/2, cos 60° = 1/2. 1/2 + 1/2 = 1.',
  },
  {
    subject: 'Mathematics',
    subsection_id: 4,
    subsection_name: 'Trigonometry',
    question_set: 'Set A',
    question_text: 'If cos θ = 12/13, where θ is acute, find tan θ.',
    options: {
      A: '5/12',
      B: '12/5',
      C: '5/13',
      D: '13/12',
    },
    correct_option: 'A',
    explanation: 'Adjacent=12, Hypotenuse=13 => Opposite = √(169-144) = 5. tan θ = 5/12.',
  },
  {
    subject: 'Mathematics',
    subsection_id: 4,
    subsection_name: 'Trigonometry',
    question_set: 'Set A',
    question_text: 'Which of the following is equal to 1?',
    options: {
      A: 'sin 30°',
      B: 'cos 60°',
      C: 'tan 45°',
      D: 'sin 60°',
    },
    correct_option: 'C',
    explanation: 'tan 45° = 1.',
  },

  // PROBABILITY AND STATISTICS (Subsection 5)
  {
    subject: 'Mathematics',
    subsection_id: 5,
    subsection_name: 'Probability and Statistics',
    question_set: 'Set A',
    question_text: 'A fair die is thrown once. What is the probability of obtaining an even number?',
    options: {
      A: '1/6',
      B: '1/3',
      C: '1/2',
      D: '2/3',
    },
    correct_option: 'C',
    explanation: 'Even outcomes are {2, 4, 6} out of 6 possible => 3/6 = 1/2.',
  },
  {
    subject: 'Mathematics',
    subsection_id: 5,
    subsection_name: 'Probability and Statistics',
    question_set: 'Set A',
    question_text: 'A bag contains 5 red, 3 blue and 2 green balls. What is the probability of selecting a blue ball?',
    options: {
      A: '1/5',
      B: '3/10',
      C: '1/3',
      D: '2/5',
    },
    correct_option: 'B',
    explanation: 'Total balls = 5+3+2 = 10. Blue balls = 3. P(Blue) = 3/10.',
  },
  {
    subject: 'Mathematics',
    subsection_id: 5,
    subsection_name: 'Probability and Statistics',
    question_set: 'Set A',
    question_text: 'Find the mean of 6, 8, 10, 12 and 14.',
    options: {
      A: '8',
      B: '9',
      C: '10',
      D: '12',
    },
    correct_option: 'C',
    explanation: 'Mean = (6+8+10+12+14)/5 = 50/5 = 10.',
  },
  {
    subject: 'Mathematics',
    subsection_id: 5,
    subsection_name: 'Probability and Statistics',
    question_set: 'Set A',
    question_text: 'Find the median of: 4, 9, 2, 7, 5, 12, 8',
    options: {
      A: '5',
      B: '7',
      C: '8',
      D: '9',
    },
    correct_option: 'B',
    explanation: 'Ordered set: {2, 4, 5, 7, 8, 9, 12}. Middle value is 7.',
  },
  {
    subject: 'Mathematics',
    subsection_id: 5,
    subsection_name: 'Probability and Statistics',
    question_set: 'Set A',
    question_text: 'The mean of five numbers is 12. If four of the numbers are 8, 10, 14 and 16, find the fifth number.',
    options: {
      A: '10',
      B: '12',
      C: '14',
      D: '16',
    },
    correct_option: 'B',
    explanation: 'Total sum = 5 * 12 = 60. Sum of 4 numbers = 48. Fifth number = 60 - 48 = 12.',
  },

  // ==================== MATHEMATICS — SET B ====================
  // GEOMETRY (Subsection 1)
  {
    subject: 'Mathematics',
    subsection_id: 1,
    subsection_name: 'Geometry',
    question_set: 'Set B',
    question_text: 'A circle has a radius of 14 cm. Using π = 22/7, find its area.',
    options: {
      A: '154 cm²',
      B: '308 cm²',
      C: '616 cm²',
      D: '1,232 cm²',
    },
    correct_option: 'C',
    explanation: 'Area = π r² = (22/7) * 14 * 14 = 22 * 28 = 616 cm².',
  },
  {
    subject: 'Mathematics',
    subsection_id: 1,
    subsection_name: 'Geometry',
    question_set: 'Set B',
    question_text: 'The perimeter of a rectangle is 50 cm. If its length is 15 cm, what is its area?',
    options: {
      A: '125 cm²',
      B: '150 cm²',
      C: '175 cm²',
      D: '200 cm²',
    },
    correct_option: 'B',
    explanation: '2*(15 + w) = 50 => 15 + w = 25 => w = 10 cm. Area = 15 * 10 = 150 cm².',
  },
  {
    subject: 'Mathematics',
    subsection_id: 1,
    subsection_name: 'Geometry',
    question_set: 'Set B',
    question_text: 'The sum of the interior angles of a polygon is 900°. How many sides does the polygon have?',
    options: {
      A: '6',
      B: '7',
      C: '8',
      D: '9',
    },
    correct_option: 'B',
    explanation: '(n - 2) * 180° = 900° => n - 2 = 5 => n = 7.',
  },
  {
    subject: 'Mathematics',
    subsection_id: 1,
    subsection_name: 'Geometry',
    question_set: 'Set B',
    question_text: 'A cuboid measures 8 cm by 5 cm by 3 cm. What is its total surface area?',
    options: {
      A: '118 cm²',
      B: '128 cm²',
      C: '158 cm²',
      D: '160 cm²',
    },
    correct_option: 'C',
    explanation: 'SA = 2(8*5 + 8*3 + 5*3) = 2(40 + 24 + 15) = 2(79) = 158 cm².',
  },
  {
    subject: 'Mathematics',
    subsection_id: 1,
    subsection_name: 'Geometry',
    question_set: 'Set B',
    question_text: 'Two angles are supplementary. If one angle is 3 times the other, find the smaller angle.',
    options: {
      A: '30°',
      B: '45°',
      C: '60°',
      D: '90°',
    },
    correct_option: 'B',
    explanation: 'x + 3x = 180° => 4x = 180° => x = 45°.',
  },

  // ALGEBRA (Subsection 2)
  {
    subject: 'Mathematics',
    subsection_id: 2,
    subsection_name: 'Algebra',
    question_set: 'Set B',
    question_text: 'Simplify: (6x²y)/(3xy)',
    options: {
      A: '2x',
      B: '2xy',
      C: '3x',
      D: '3xy',
    },
    correct_option: 'A',
    explanation: '(6/3) * (x²/x) * (y/y) = 2x.',
  },
  {
    subject: 'Mathematics',
    subsection_id: 2,
    subsection_name: 'Algebra',
    question_set: 'Set B',
    question_text: 'If 2x + 3y = 12 and x = 3, find y.',
    options: {
      A: '1',
      B: '2',
      C: '3',
      D: '4',
    },
    correct_option: 'B',
    explanation: '2(3) + 3y = 12 => 6 + 3y = 12 => 3y = 6 => y = 2.',
  },
  {
    subject: 'Mathematics',
    subsection_id: 2,
    subsection_name: 'Algebra',
    question_set: 'Set B',
    question_text: 'Expand: (x + 4)(x − 2)',
    options: {
      A: 'x² + 2x − 8',
      B: 'x² − 2x − 8',
      C: 'x² + 6x + 8',
      D: 'x² − 6x − 8',
    },
    correct_option: 'A',
    explanation: 'x² - 2x + 4x - 8 = x² + 2x - 8.',
  },
  {
    subject: 'Mathematics',
    subsection_id: 2,
    subsection_name: 'Algebra',
    question_set: 'Set B',
    question_text: 'Solve: x² − 9 = 0',
    options: {
      A: 'x = 3 only',
      B: 'x = −3 only',
      C: 'x = ±3',
      D: 'x = ±9',
    },
    correct_option: 'C',
    explanation: 'x² = 9 => x = ±3.',
  },
  {
    subject: 'Mathematics',
    subsection_id: 2,
    subsection_name: 'Algebra',
    question_set: 'Set B',
    question_text: 'If x/3 + 2 = 6, what is x?',
    options: {
      A: '6',
      B: '9',
      C: '12',
      D: '18',
    },
    correct_option: 'C',
    explanation: 'x/3 = 4 => x = 12.',
  },

  // SET THEORY (Subsection 3)
  {
    subject: 'Mathematics',
    subsection_id: 3,
    subsection_name: 'Set Theory',
    question_set: 'Set B',
    question_text: "Let U = {1,2,3,4,5,6,7,8,9,10} and A = {2,4,6,8,10}. What is A'?",
    options: {
      A: '{1,3,5,7,9}',
      B: '{2,4,6,8}',
      C: '{1,2,3,5,7,9}',
      D: '{5,7,9,10}',
    },
    correct_option: 'A',
    explanation: "Complement A' contains elements in U not in A => {1,3,5,7,9}.",
  },
  {
    subject: 'Mathematics',
    subsection_id: 3,
    subsection_name: 'Set Theory',
    question_set: 'Set B',
    question_text: 'If A = {a, b, c} and B = {b, c, d}, how many elements are in A ∪ B?',
    options: {
      A: '2',
      B: '3',
      C: '4',
      D: '6',
    },
    correct_option: 'C',
    explanation: 'A ∪ B = {a, b, c, d}, count is 4.',
  },
  {
    subject: 'Mathematics',
    subsection_id: 3,
    subsection_name: 'Set Theory',
    question_set: 'Set B',
    question_text: 'Which statement is always true?',
    options: {
      A: 'A ∩ B contains all elements of A and B',
      B: 'A ∪ B contains elements common to A and B only',
      C: 'A ∩ B is a subset of A',
      D: 'A ∪ B is a subset of A',
    },
    correct_option: 'C',
    explanation: 'By set definition, the intersection A ∩ B is a subset of set A.',
  },
  {
    subject: 'Mathematics',
    subsection_id: 3,
    subsection_name: 'Set Theory',
    question_set: 'Set B',
    question_text: "If n(U) = 50 and n(A) = 32, find n(A').",
    options: {
      A: '12',
      B: '18',
      C: '20',
      D: '22',
    },
    correct_option: 'B',
    explanation: "n(A') = n(U) - n(A) = 50 - 32 = 18.",
  },
  {
    subject: 'Mathematics',
    subsection_id: 3,
    subsection_name: 'Set Theory',
    question_set: 'Set B',
    question_text: 'If A = {1,2,3} and B = {3,4,5}, what is the number of elements in A × B?',
    options: {
      A: '3',
      B: '5',
      C: '6',
      D: '9',
    },
    correct_option: 'D',
    explanation: 'n(A × B) = n(A) * n(B) = 3 * 3 = 9.',
  },

  // TRIGONOMETRY (Subsection 4)
  {
    subject: 'Mathematics',
    subsection_id: 4,
    subsection_name: 'Trigonometry',
    question_set: 'Set B',
    question_text: 'A ladder 10 m long leans against a vertical wall. If the ladder makes an angle of 30° with the ground, how high up the wall does it reach?',
    options: {
      A: '5 m',
      B: '5√2 m',
      C: '5√3 m',
      D: '10√3 m',
    },
    correct_option: 'A',
    explanation: 'height = 10 * sin 30° = 10 * 0.5 = 5 m.',
  },
  {
    subject: 'Mathematics',
    subsection_id: 4,
    subsection_name: 'Trigonometry',
    question_set: 'Set B',
    question_text: 'If tan θ = 1/√3, what is θ?',
    options: {
      A: '30°',
      B: '45°',
      C: '60°',
      D: '90°',
    },
    correct_option: 'A',
    explanation: 'arctan(1/√3) = 30°.',
  },
  {
    subject: 'Mathematics',
    subsection_id: 4,
    subsection_name: 'Trigonometry',
    question_set: 'Set B',
    question_text: 'Evaluate: cos² 30° + sin² 30°',
    options: {
      A: '0',
      B: '1/2',
      C: '1',
      D: '2',
    },
    correct_option: 'C',
    explanation: 'Pythagorean identity cos²θ + sin²θ = 1.',
  },
  {
    subject: 'Mathematics',
    subsection_id: 4,
    subsection_name: 'Trigonometry',
    question_set: 'Set B',
    question_text: 'A right-angled triangle has an opposite side of 8 cm and hypotenuse of 17 cm. Find sin θ.',
    options: {
      A: '8/15',
      B: '8/17',
      C: '15/17',
      D: '17/8',
    },
    correct_option: 'B',
    explanation: 'sin θ = opposite / hypotenuse = 8/17.',
  },
  {
    subject: 'Mathematics',
    subsection_id: 4,
    subsection_name: 'Trigonometry',
    question_set: 'Set B',
    question_text: 'If sin θ = 0.6, what is cos²θ?',
    options: {
      A: '0.16',
      B: '0.36',
      C: '0.64',
      D: '0.80',
    },
    correct_option: 'C',
    explanation: 'cos²θ = 1 - sin²θ = 1 - 0.36 = 0.64.',
  },

  // PROBABILITY AND STATISTICS (Subsection 5)
  {
    subject: 'Mathematics',
    subsection_id: 5,
    subsection_name: 'Probability and Statistics',
    question_set: 'Set B',
    question_text: 'A coin is tossed twice. What is the probability of getting two heads?',
    options: {
      A: '1/2',
      B: '1/3',
      C: '1/4',
      D: '1/8',
    },
    correct_option: 'C',
    explanation: 'P(HH) = (1/2) * (1/2) = 1/4.',
  },
  {
    subject: 'Mathematics',
    subsection_id: 5,
    subsection_name: 'Probability and Statistics',
    question_set: 'Set B',
    question_text: 'Find the range of the following data: 12, 7, 15, 9, 20, 11',
    options: {
      A: '11',
      B: '12',
      C: '13',
      D: '15',
    },
    correct_option: 'C',
    explanation: 'Range = Max - Min = 20 - 7 = 13.',
  },
  {
    subject: 'Mathematics',
    subsection_id: 5,
    subsection_name: 'Probability and Statistics',
    question_set: 'Set B',
    question_text: 'The scores of five students are 12, 15, 18, 15 and 20. What is the mode?',
    options: {
      A: '12',
      B: '15',
      C: '18',
      D: '20',
    },
    correct_option: 'B',
    explanation: 'Mode is the most frequently occurring value (15 appears twice).',
  },
  {
    subject: 'Mathematics',
    subsection_id: 5,
    subsection_name: 'Probability and Statistics',
    question_set: 'Set B',
    question_text: 'A card is selected randomly from a standard pack of 52 cards. What is the probability of selecting an ace?',
    options: {
      A: '1/52',
      B: '1/26',
      C: '1/13',
      D: '4/13',
    },
    correct_option: 'C',
    explanation: 'P(Ace) = 4 / 52 = 1/13.',
  },
  {
    subject: 'Mathematics',
    subsection_id: 5,
    subsection_name: 'Probability and Statistics',
    question_set: 'Set B',
    question_text: "If P(A) = 0.35, what is P(A')?",
    options: {
      A: '0.35',
      B: '0.55',
      C: '0.65',
      D: '1.35',
    },
    correct_option: 'C',
    explanation: "P(A') = 1 - P(A) = 1 - 0.35 = 0.65.",
  },

  // ==================== PHYSICS — SET A ====================
  // CLASSICAL MECHANICS (Subsection 1)
  {
    subject: 'Physics',
    subsection_id: 1,
    subsection_name: 'Classical Mechanics',
    question_set: 'Set A',
    question_text: 'A car starts from rest and accelerates uniformly at 2 m/s² for 6 s. What is its final velocity?',
    options: {
      A: '6 m/s',
      B: '8 m/s',
      C: '12 m/s',
      D: '18 m/s',
    },
    correct_option: 'C',
    explanation: 'v = u + at = 0 + (2 * 6) = 12 m/s.',
  },
  {
    subject: 'Physics',
    subsection_id: 1,
    subsection_name: 'Classical Mechanics',
    question_set: 'Set A',
    question_text: "Which statement best describes Newton's first law?",
    options: {
      A: 'Force is always mass × acceleration',
      B: 'A body remains at rest or uniform velocity unless acted on by a resultant external force',
      C: 'Every action has an equal reaction',
      D: 'Momentum is always zero',
    },
    correct_option: 'B',
    explanation: "Newton's first law defines inertia and net force requirement for state change.",
  },
  {
    subject: 'Physics',
    subsection_id: 1,
    subsection_name: 'Classical Mechanics',
    question_set: 'Set A',
    question_text: 'A 4 kg object is acted upon by a resultant force of 20 N. Its acceleration is:',
    options: {
      A: '0.2 m/s²',
      B: '5 m/s²',
      C: '16 m/s²',
      D: '80 m/s²',
    },
    correct_option: 'B',
    explanation: 'a = F / m = 20 / 4 = 5 m/s².',
  },
  {
    subject: 'Physics',
    subsection_id: 1,
    subsection_name: 'Classical Mechanics',
    question_set: 'Set A',
    question_text: 'A stone is thrown vertically upward. At maximum height its:',
    options: {
      A: 'velocity and acceleration are both zero',
      B: 'velocity is zero but acceleration is not zero',
      C: 'velocity is maximum',
      D: 'acceleration is zero',
    },
    correct_option: 'B',
    explanation: 'Instantaneous velocity is zero while downward gravitational acceleration g persists.',
  },
  {
    subject: 'Physics',
    subsection_id: 1,
    subsection_name: 'Classical Mechanics',
    question_set: 'Set A',
    question_text: 'A 2 kg object moving at 5 m/s has kinetic energy:',
    options: {
      A: '5 J',
      B: '10 J',
      C: '25 J',
      D: '50 J',
    },
    correct_option: 'C',
    explanation: 'KE = 0.5 * m * v² = 0.5 * 2 * 25 = 25 J.',
  },

  // HEAT AND ENERGY (Subsection 2)
  {
    subject: 'Physics',
    subsection_id: 2,
    subsection_name: 'Heat and Energy',
    question_set: 'Set A',
    question_text: 'Specific heat capacity is the heat required to raise the temperature of:',
    options: {
      A: '1 kg of a substance by 1°C',
      B: 'any mass by 10°C',
      C: '1 g of water by 1°C',
      D: '1 kg to its melting point',
    },
    correct_option: 'A',
    explanation: 'Specific heat capacity c = Q / (m * ΔT).',
  },
  {
    subject: 'Physics',
    subsection_id: 2,
    subsection_name: 'Heat and Energy',
    question_set: 'Set A',
    question_text: 'Heat needed to raise 2 kg of water through 10°C, c = 4,200 J kg⁻¹ °C⁻¹, is:',
    options: {
      A: '8,400 J',
      B: '21,000 J',
      C: '42,000 J',
      D: '84,000 J',
    },
    correct_option: 'D',
    explanation: 'Q = m c ΔT = 2 * 4200 * 10 = 84,000 J.',
  },
  {
    subject: 'Physics',
    subsection_id: 2,
    subsection_name: 'Heat and Energy',
    question_set: 'Set A',
    question_text: 'During boiling of a pure liquid at constant pressure, its temperature:',
    options: {
      A: 'increases',
      B: 'decreases',
      C: 'remains constant',
      D: 'becomes zero',
    },
    correct_option: 'C',
    explanation: 'Latent heat of vaporization causes phase change at constant boiling temperature.',
  },
  {
    subject: 'Physics',
    subsection_id: 2,
    subsection_name: 'Heat and Energy',
    question_set: 'Set A',
    question_text: 'Which heat-transfer method needs no material medium?',
    options: {
      A: 'Conduction',
      B: 'Convection',
      C: 'Radiation',
      D: 'All need a medium',
    },
    correct_option: 'C',
    explanation: 'Thermal radiation travels via electromagnetic waves through a vacuum.',
  },
  {
    subject: 'Physics',
    subsection_id: 2,
    subsection_name: 'Heat and Energy',
    question_set: 'Set A',
    question_text: 'The first law of thermodynamics expresses conservation of:',
    options: {
      A: 'momentum',
      B: 'charge',
      C: 'energy',
      D: 'mass only',
    },
    correct_option: 'C',
    explanation: 'First law: ΔU = Q - W (Conservation of Energy).',
  },

  // WAVES (Subsection 3)
  {
    subject: 'Physics',
    subsection_id: 3,
    subsection_name: 'Waves',
    question_set: 'Set A',
    question_text: 'A wave has a frequency of 50 Hz and a wavelength of 2.0 m. What is its speed?',
    options: {
      A: '25 m/s',
      B: '50 m/s',
      C: '100 m/s',
      D: '200 m/s',
    },
    correct_option: 'C',
    explanation: 'v = f * λ = 50 * 2.0 = 100 m/s.',
  },
  {
    subject: 'Physics',
    subsection_id: 3,
    subsection_name: 'Waves',
    question_set: 'Set A',
    question_text: 'Which statement correctly distinguishes a transverse wave from a longitudinal wave?',
    options: {
      A: 'Particles vibrate parallel to wave direction in a transverse wave',
      B: 'Particles vibrate perpendicular to wave direction in a transverse wave',
      C: 'Both types always require a material medium',
      D: 'Only longitudinal waves can be reflected',
    },
    correct_option: 'B',
    explanation: 'Transverse wave particle displacement is perpendicular to wave propagation.',
  },
  {
    subject: 'Physics',
    subsection_id: 3,
    subsection_name: 'Waves',
    question_set: 'Set A',
    question_text: 'When a wave passes from one medium into another, which quantity remains unchanged?',
    options: {
      A: 'Speed',
      B: 'Wavelength',
      C: 'Frequency',
      D: 'Amplitude',
    },
    correct_option: 'C',
    explanation: 'Frequency depends solely on the wave source and remains invariant during refraction.',
  },
  {
    subject: 'Physics',
    subsection_id: 3,
    subsection_name: 'Waves',
    question_set: 'Set A',
    question_text: 'The bending of waves around obstacles or through narrow openings is known as:',
    options: {
      A: 'Reflection',
      B: 'Refraction',
      C: 'Diffraction',
      D: 'Dispersion',
    },
    correct_option: 'C',
    explanation: 'Diffraction is wave spreading around obstacle edges or through apertures.',
  },
  {
    subject: 'Physics',
    subsection_id: 3,
    subsection_name: 'Waves',
    question_set: 'Set A',
    question_text: 'A sound wave travels at 340 m/s and has a frequency of 680 Hz. What is its wavelength?',
    options: {
      A: '0.25 m',
      B: '0.50 m',
      C: '1.0 m',
      D: '2.0 m',
    },
    correct_option: 'B',
    explanation: 'λ = v / f = 340 / 680 = 0.50 m.',
  },

  // ELECTRICITY AND MAGNETISM (Subsection 4)
  {
    subject: 'Physics',
    subsection_id: 4,
    subsection_name: 'Electricity and Magnetism',
    question_set: 'Set A',
    question_text: 'A 12 V supply is connected to a 6 Ω resistor. Current is:',
    options: {
      A: '0.5 A',
      B: '2 A',
      C: '6 A',
      D: '72 A',
    },
    correct_option: 'B',
    explanation: 'I = V / R = 12 / 6 = 2 A.',
  },
  {
    subject: 'Physics',
    subsection_id: 4,
    subsection_name: 'Electricity and Magnetism',
    question_set: 'Set A',
    question_text: "Which equation represents Ohm's law?",
    options: {
      A: 'P=VI',
      B: 'V=IR',
      C: 'Q=It',
      D: 'E=Pt',
    },
    correct_option: 'B',
    explanation: "Ohm's law: V = I * R.",
  },
  {
    subject: 'Physics',
    subsection_id: 4,
    subsection_name: 'Electricity and Magnetism',
    question_set: 'Set A',
    question_text: '4 Ω and 6 Ω resistors in series have combined resistance:',
    options: {
      A: '2.4 Ω',
      B: '5 Ω',
      C: '10 Ω',
      D: '24 Ω',
    },
    correct_option: 'C',
    explanation: 'R_total = R1 + R2 = 4 + 6 = 10 Ω.',
  },
  {
    subject: 'Physics',
    subsection_id: 4,
    subsection_name: 'Electricity and Magnetism',
    question_set: 'Set A',
    question_text: '6 Ω and 3 Ω resistors in parallel have equivalent resistance:',
    options: {
      A: '2 Ω',
      B: '3 Ω',
      C: '9 Ω',
      D: '18 Ω',
    },
    correct_option: 'A',
    explanation: 'R_eq = (6 * 3) / (6 + 3) = 18 / 9 = 2 Ω.',
  },
  {
    subject: 'Physics',
    subsection_id: 4,
    subsection_name: 'Electricity and Magnetism',
    question_set: 'Set A',
    question_text: 'Electrical power is given by:',
    options: {
      A: 'P=VI',
      B: 'P=V/I',
      C: 'P=IR',
      D: 'P=I/R',
    },
    correct_option: 'A',
    explanation: 'P = V * I.',
  },

  // MODERN PHYSICS (Subsection 5)
  {
    subject: 'Physics',
    subsection_id: 5,
    subsection_name: 'Modern Physics',
    question_set: 'Set A',
    question_text: 'Photon energy is given by:',
    options: {
      A: 'E=mc²',
      B: 'E=hf',
      C: 'E=IR',
      D: 'E=Pt',
    },
    correct_option: 'B',
    explanation: "Planck's relation E = h * f.",
  },
  {
    subject: 'Physics',
    subsection_id: 5,
    subsection_name: 'Modern Physics',
    question_set: 'Set A',
    question_text: 'Energy of a photon of frequency 5×10¹⁴ Hz, h=6.63×10⁻³⁴ Js, is:',
    options: {
      A: '1.33×10⁻¹⁹ J',
      B: '3.32×10⁻¹⁹ J',
      C: '6.63×10⁻³⁴ J',
      D: '3.32×10⁻²⁰ J',
    },
    correct_option: 'B',
    explanation: 'E = hf = 6.63×10⁻³⁴ * 5×10¹⁴ = 3.315×10⁻¹⁹ ≈ 3.32×10⁻¹⁹ J.',
  },
  {
    subject: 'Physics',
    subsection_id: 5,
    subsection_name: 'Modern Physics',
    question_set: 'Set A',
    question_text: 'The photoelectric effect shows that light can behave as:',
    options: {
      A: 'only a continuous wave',
      B: 'particles called photons',
      C: 'sound waves',
      D: 'matter only',
    },
    correct_option: 'B',
    explanation: 'Photoelectric emission demonstrates light quantum particle nature.',
  },
  {
    subject: 'Physics',
    subsection_id: 5,
    subsection_name: 'Modern Physics',
    question_set: 'Set A',
    question_text: 'Minimum frequency needed to eject electrons from a metal is:',
    options: {
      A: 'threshold frequency',
      B: 'resonant frequency',
      C: 'natural frequency',
      D: 'critical speed',
    },
    correct_option: 'A',
    explanation: 'Threshold frequency f_0 corresponds to metal work function Φ.',
  },
  {
    subject: 'Physics',
    subsection_id: 5,
    subsection_name: 'Modern Physics',
    question_set: 'Set A',
    question_text: 'A radioactive sample has a half-life of 4 hours. Fraction remaining after 12 hours is:',
    options: {
      A: '1/8',
      B: '1/2',
      C: '1/4',
      D: '1/16',
    },
    correct_option: 'A',
    explanation: 'Number of half-lives n = 12/4 = 3. Fraction = (1/2)³ = 1/8.',
  },

  // ==================== PHYSICS — SET B ====================
  // CLASSICAL MECHANICS (Subsection 1)
  {
    subject: 'Physics',
    subsection_id: 1,
    subsection_name: 'Classical Mechanics',
    question_set: 'Set B',
    question_text: 'Conservation of linear momentum applies when:',
    options: {
      A: 'resultant external force on the system is zero',
      B: 'objects have equal masses',
      C: 'collision is always elastic',
      D: 'bodies are stationary',
    },
    correct_option: 'A',
    explanation: 'Net external force F_ext = dp/dt = 0 implies momentum p is conserved.',
  },
  {
    subject: 'Physics',
    subsection_id: 1,
    subsection_name: 'Classical Mechanics',
    question_set: 'Set B',
    question_text: '10 kg box is pulled by 40 N while friction is 15 N. Its acceleration is:',
    options: {
      A: '1.5 m/s²',
      B: '2.5 m/s²',
      C: '4.0 m/s²',
      D: '5.5 m/s²',
    },
    correct_option: 'B',
    explanation: 'Net force = 40 - 15 = 25 N. a = 25 / 10 = 2.5 m/s².',
  },
  {
    subject: 'Physics',
    subsection_id: 1,
    subsection_name: 'Classical Mechanics',
    question_set: 'Set B',
    question_text: 'Which quantity is a vector?',
    options: {
      A: 'Mass',
      B: 'Speed',
      C: 'Energy',
      D: 'Momentum',
    },
    correct_option: 'D',
    explanation: 'Momentum p = mv has both magnitude and direction.',
  },
  {
    subject: 'Physics',
    subsection_id: 1,
    subsection_name: 'Classical Mechanics',
    question_set: 'Set B',
    question_text: 'A force of 30 N moves an object 4 m in its direction. Work done is:',
    options: {
      A: '7.5 J',
      B: '26 J',
      C: '120 J',
      D: '240 J',
    },
    correct_option: 'C',
    explanation: 'W = F * d = 30 * 4 = 120 J.',
  },
  {
    subject: 'Physics',
    subsection_id: 1,
    subsection_name: 'Classical Mechanics',
    question_set: 'Set B',
    question_text: "Newton's third-law forces:",
    options: {
      A: 'act on the same body',
      B: 'are equal and opposite and act on different bodies',
      C: 'are unequal for different masses',
      D: 'always cancel each other',
    },
    correct_option: 'B',
    explanation: 'Action-reaction pairs act simultaneously on interacting distinct bodies.',
  },

  // HEAT AND ENERGY (Subsection 2)
  {
    subject: 'Physics',
    subsection_id: 2,
    subsection_name: 'Heat and Energy',
    question_set: 'Set B',
    question_text: 'A machine takes in 2,000 J and gives 500 J useful output. Efficiency is:',
    options: {
      A: '10%',
      B: '20%',
      C: '25%',
      D: '40%',
    },
    correct_option: 'C',
    explanation: 'Efficiency = (Useful Output / Total Input) * 100% = (500 / 2000) * 100% = 25%.',
  },
  {
    subject: 'Physics',
    subsection_id: 2,
    subsection_name: 'Heat and Energy',
    question_set: 'Set B',
    question_text: 'Which change involves latent heat?',
    options: {
      A: 'Heating water from 20°C to 40°C',
      B: 'Melting ice at its melting point',
      C: 'Heating a metal',
      D: 'Cooling steam without phase change',
    },
    correct_option: 'B',
    explanation: 'Melting ice absorbs latent heat of fusion at constant 0°C temperature.',
  },
  {
    subject: 'Physics',
    subsection_id: 2,
    subsection_name: 'Heat and Energy',
    question_set: 'Set B',
    question_text: 'Cooking pots commonly have metal bodies because metals are:',
    options: {
      A: 'poor conductors',
      B: 'good conductors',
      C: 'unable to absorb heat',
      D: 'insulators',
    },
    correct_option: 'B',
    explanation: 'Metals possess high thermal conductivity via free electron heat transfer.',
  },
  {
    subject: 'Physics',
    subsection_id: 2,
    subsection_name: 'Heat and Energy',
    question_set: 'Set B',
    question_text: 'For an ideal gas at constant volume, increasing temperature causes pressure to:',
    options: {
      A: 'decrease',
      B: 'remain constant',
      C: 'increase',
      D: 'become zero',
    },
    correct_option: 'C',
    explanation: "Gay-Lussac's Law: P ∝ T at constant volume.",
  },
  {
    subject: 'Physics',
    subsection_id: 2,
    subsection_name: 'Heat and Energy',
    question_set: 'Set B',
    question_text: 'A gas receives 500 J of heat and does 300 J of work. Its increase in internal energy is:',
    options: {
      A: '200 J',
      B: '300 J',
      C: '500 J',
      D: '800 J',
    },
    correct_option: 'A',
    explanation: 'ΔU = Q - W = 500 - 300 = 200 J.',
  },

  // WAVES (Subsection 3)
  {
    subject: 'Physics',
    subsection_id: 3,
    subsection_name: 'Waves',
    question_set: 'Set B',
    question_text: 'An echo is heard 0.60 s after a sound is produced. If the speed of sound is 340 m/s, how far is the reflecting surface from the source?',
    options: {
      A: '51 m',
      B: '102 m',
      C: '204 m',
      D: '340 m',
    },
    correct_option: 'B',
    explanation: 'Total distance = v * t = 340 * 0.60 = 204 m. Surface distance d = 204 / 2 = 102 m.',
  },
  {
    subject: 'Physics',
    subsection_id: 3,
    subsection_name: 'Waves',
    question_set: 'Set B',
    question_text: 'Which statement about electromagnetic waves is correct?',
    options: {
      A: 'They require a material medium to travel',
      B: 'They are all longitudinal',
      C: 'They can travel through a vacuum',
      D: 'They all have the same frequency',
    },
    correct_option: 'C',
    explanation: 'Electromagnetic waves consist of oscillating electric & magnetic fields propagating through vacuum at speed c.',
  },
  {
    subject: 'Physics',
    subsection_id: 3,
    subsection_name: 'Waves',
    question_set: 'Set B',
    question_text: 'Which region of the electromagnetic spectrum has the highest frequency?',
    options: {
      A: 'Radio waves',
      B: 'Microwaves',
      C: 'Visible light',
      D: 'Gamma rays',
    },
    correct_option: 'D',
    explanation: 'Gamma rays possess the shortest wavelength and highest frequency/photon energy.',
  },
  {
    subject: 'Physics',
    subsection_id: 3,
    subsection_name: 'Waves',
    question_set: 'Set B',
    question_text: 'Light enters glass from air. Which combination is correct?',
    options: {
      A: 'Speed increases and frequency increases',
      B: 'Speed decreases while frequency remains unchanged',
      C: 'Speed remains unchanged and wavelength increases',
      D: 'Frequency decreases while speed increases',
    },
    correct_option: 'B',
    explanation: 'Glass is optically denser, slowing speed v while frequency f remains constant.',
  },
  {
    subject: 'Physics',
    subsection_id: 3,
    subsection_name: 'Waves',
    question_set: 'Set B',
    question_text: 'A converging lens has a focal length of 10 cm and an object is placed 30 cm from the lens. The image distance is:',
    options: {
      A: '5 cm',
      B: '10 cm',
      C: '15 cm',
      D: '30 cm',
    },
    correct_option: 'C',
    explanation: '1/v = 1/f - 1/u = 1/10 - 1/30 = 2/30 => v = 15 cm.',
  },

  // ELECTRICITY AND MAGNETISM (Subsection 4)
  {
    subject: 'Physics',
    subsection_id: 4,
    subsection_name: 'Electricity and Magnetism',
    question_set: 'Set B',
    question_text: 'A 100 W appliance runs for 5 hours. Energy consumed is:',
    options: {
      A: '20 Wh',
      B: '100 Wh',
      C: '500 Wh',
      D: '2,000 Wh',
    },
    correct_option: 'C',
    explanation: 'E = P * t = 100 W * 5 h = 500 Wh.',
  },
  {
    subject: 'Physics',
    subsection_id: 4,
    subsection_name: 'Electricity and Magnetism',
    question_set: 'Set B',
    question_text: 'The law relating induced e.m.f. to rate of change of magnetic flux linkage is:',
    options: {
      A: "Ohm's law",
      B: "Faraday's law",
      C: "Kirchhoff's first law",
      D: "Coulomb's law",
    },
    correct_option: 'B',
    explanation: "Faraday's law: Induced EMF ε = -dΦ/dt.",
  },
  {
    subject: 'Physics',
    subsection_id: 4,
    subsection_name: 'Electricity and Magnetism',
    question_set: 'Set B',
    question_text: 'Force on a current-carrying conductor is greatest when it is:',
    options: {
      A: 'parallel to field',
      B: 'perpendicular to field',
      C: 'at 45°',
      D: 'outside field',
    },
    correct_option: 'B',
    explanation: 'F = B I L sin θ is maximum when θ = 90° (perpendicular).',
  },
  {
    subject: 'Physics',
    subsection_id: 4,
    subsection_name: 'Electricity and Magnetism',
    question_set: 'Set B',
    question_text: 'A transformer has 500 primary and 100 secondary turns. Primary voltage is 240 V. Secondary voltage is:',
    options: {
      A: '24 V',
      B: '48 V',
      C: '120 V',
      D: '1,200 V',
    },
    correct_option: 'B',
    explanation: 'Vs / Vp = Ns / Np => Vs / 240 = 100 / 500 => Vs = 48 V.',
  },
  {
    subject: 'Physics',
    subsection_id: 4,
    subsection_name: 'Electricity and Magnetism',
    question_set: 'Set B',
    question_text: 'A device converting mechanical energy to electrical energy by electromagnetic induction is a:',
    options: {
      A: 'motor',
      B: 'generator',
      C: 'transformer',
      D: 'capacitor',
    },
    correct_option: 'B',
    explanation: 'Electric generators convert mechanical rotation into electrical energy via induction.',
  },

  // MODERN PHYSICS (Subsection 5)
  {
    subject: 'Physics',
    subsection_id: 5,
    subsection_name: 'Modern Physics',
    question_set: 'Set B',
    question_text: 'Which radiation has the greatest penetrating power?',
    options: {
      A: 'Alpha',
      B: 'Beta',
      C: 'Gamma',
      D: 'All equal',
    },
    correct_option: 'C',
    explanation: 'Gamma rays are high-energy photons requiring dense lead/concrete shielding.',
  },
  {
    subject: 'Physics',
    subsection_id: 5,
    subsection_name: 'Modern Physics',
    question_set: 'Set B',
    question_text: 'An alpha particle is essentially a:',
    options: {
      A: 'fast electron',
      B: 'helium nucleus',
      C: 'photon',
      D: 'neutron',
    },
    correct_option: 'B',
    explanation: 'Alpha particles are ⁴₂He²⁺ nuclei (2 protons and 2 neutrons).',
  },
  {
    subject: 'Physics',
    subsection_id: 5,
    subsection_name: 'Modern Physics',
    question_set: 'Set B',
    question_text: 'Nuclear fission involves:',
    options: {
      A: 'joining light nuclei',
      B: 'splitting a heavy nucleus',
      C: 'removing an electron',
      D: 'converting heat to light',
    },
    correct_option: 'B',
    explanation: 'Fission is the splitting of a heavy radioactive nucleus into lighter fragments.',
  },
  {
    subject: 'Physics',
    subsection_id: 5,
    subsection_name: 'Modern Physics',
    question_set: 'Set B',
    question_text: "Einstein's mass-energy relation is:",
    options: {
      A: 'E=mc',
      B: 'E=mc²',
      C: 'E=m/c²',
      D: 'E=m²c',
    },
    correct_option: 'B',
    explanation: 'E = m * c².',
  },
  {
    subject: 'Physics',
    subsection_id: 5,
    subsection_name: 'Modern Physics',
    question_set: 'Set B',
    question_text: 'A metal has a work function of 2.0 eV. Photon energy is 3.5 eV. Maximum electron kinetic energy is:',
    options: {
      A: '1.5 eV',
      B: '2.0 eV',
      C: '3.5 eV',
      D: '5.5 eV',
    },
    correct_option: 'A',
    explanation: 'KE_max = hf - Φ = 3.5 - 2.0 = 1.5 eV.',
  },

  // ==================== CHEMISTRY — SET A ====================
  // BASIC CHEMISTRY (Subsection 1)
  {
    subject: 'Chemistry',
    subsection_id: 1,
    subsection_name: 'Basic Chemistry',
    question_set: 'Set A',
    question_text: 'What is the number of atoms present in 0.5 moles of carbon-12?',
    options: {
      A: '6.02 × 10²³',
      B: '3.01 × 10²³',
      C: '1.20 × 10²⁴',
      D: '1.50 × 10²³',
    },
    correct_option: 'B',
    explanation: 'Atoms = moles * N_A = 0.5 * 6.02×10²³ = 3.01×10²³.',
  },
  {
    subject: 'Chemistry',
    subsection_id: 1,
    subsection_name: 'Basic Chemistry',
    question_set: 'Set A',
    question_text: 'What is the empirical formula of a compound that contains 40.0% carbon, 6.7% hydrogen, and 53.3% oxygen by mass?',
    options: {
      A: 'C₂H₄O₂',
      B: 'CH₂O',
      C: 'CHO₂',
      D: 'C₂H₆O',
    },
    correct_option: 'B',
    explanation: 'Moles: C = 40/12 = 3.33; H = 6.7/1 = 6.7; O = 53.3/16 = 3.33. Ratio C:H:O = 1:2:1 => CH₂O.',
  },
  {
    subject: 'Chemistry',
    subsection_id: 1,
    subsection_name: 'Basic Chemistry',
    question_set: 'Set A',
    question_text: 'Which quantum number defines the specific spatial orientation of an atomic orbital?',
    options: {
      A: 'Principal quantum number (n)',
      B: 'Azimuthal quantum number (l)',
      C: 'Magnetic quantum number (m_l)',
      D: 'Spin quantum number (m_s)',
    },
    correct_option: 'C',
    explanation: 'Magnetic quantum number m_l determines orbital orientation in space.',
  },
  {
    subject: 'Chemistry',
    subsection_id: 1,
    subsection_name: 'Basic Chemistry',
    question_set: 'Set A',
    question_text: 'What is the oxidation state of manganese in the permanganate ion (MnO₄⁻)?',
    options: {
      A: '+5',
      B: '+6',
      C: '+7',
      D: '+8',
    },
    correct_option: 'C',
    explanation: 'x + 4(-2) = -1 => x - 8 = -1 => x = +7.',
  },
  {
    subject: 'Chemistry',
    subsection_id: 1,
    subsection_name: 'Basic Chemistry',
    question_set: 'Set A',
    question_text: 'What is the ground-state electron configuration of a neutral copper atom?',
    options: {
      A: '[Ar] 4s² 3d⁹',
      B: '[Ar] 4s¹ 3d¹⁰',
      C: '[Ar] 4s² 3d⁸',
      D: '[Ar] 4s⁰ 3d¹⁰',
    },
    correct_option: 'B',
    explanation: 'Copper exhibits anomalous subshell stability: [Ar] 4s¹ 3d¹⁰.',
  },

  // INORGANIC CHEMISTRY (Subsection 2)
  {
    subject: 'Chemistry',
    subsection_id: 2,
    subsection_name: 'Inorganic Chemistry',
    question_set: 'Set A',
    question_text: 'Which element in Period 3 of the periodic table exhibits the highest first ionization energy?',
    options: {
      A: 'Chlorine',
      B: 'Argon',
      C: 'Sodium',
      D: 'Phosphorus',
    },
    correct_option: 'B',
    explanation: 'Argon has a stable octet noble gas configuration.',
  },
  {
    subject: 'Chemistry',
    subsection_id: 2,
    subsection_name: 'Inorganic Chemistry',
    question_set: 'Set A',
    question_text: 'What is the conjugate base of the dihydrogen phosphate ion (H₂PO₄⁻)?',
    options: {
      A: 'H₃PO₄',
      B: 'HPO₄²⁻',
      C: 'PO₄³⁻',
      D: 'OH⁻',
    },
    correct_option: 'B',
    explanation: 'Removing one proton H⁺ from H₂PO₄⁻ yields HPO₄²⁻.',
  },
  {
    subject: 'Chemistry',
    subsection_id: 2,
    subsection_name: 'Inorganic Chemistry',
    question_set: 'Set A',
    question_text: 'Which halogen exists as a dark red liquid at standard room temperature and pressure?',
    options: {
      A: 'Fluorine',
      B: 'Chlorine',
      C: 'Bromine',
      D: 'Iodine',
    },
    correct_option: 'C',
    explanation: 'Bromine (Br₂) is the only liquid non-metal halogen at STP.',
  },
  {
    subject: 'Chemistry',
    subsection_id: 2,
    subsection_name: 'Inorganic Chemistry',
    question_set: 'Set A',
    question_text: 'What is the formula of the complex ion formed when excess aqueous ammonia is added to a solution of copper(II) sulfate?',
    options: {
      A: '[Cu(NH₃)₂]²⁺',
      B: '[Cu(NH₃)₄(H₂O)₂]²⁺',
      C: '[Cu(NH₃)₆]²⁺',
      D: '[Cu(OH)₄]²⁻',
    },
    correct_option: 'B',
    explanation: 'Tetraamminediacquacopper(II) complex gives deep royal blue solution.',
  },
  {
    subject: 'Chemistry',
    subsection_id: 2,
    subsection_name: 'Inorganic Chemistry',
    question_set: 'Set A',
    question_text: 'Which of the following oxides is considered amphoteric?',
    options: {
      A: 'Na₂O',
      B: 'MgO',
      C: 'Al₂O₃',
      D: 'SO₃',
    },
    correct_option: 'C',
    explanation: 'Aluminium oxide (Al₂O₃) reacts with both acids and bases.',
  },

  // PHYSICAL CHEMISTRY (Subsection 3)
  {
    subject: 'Chemistry',
    subsection_id: 3,
    subsection_name: 'Physical Chemistry',
    question_set: 'Set A',
    question_text: 'What is the overall reaction order for a chemical reaction with the rate law: Rate = k[A]²[B]?',
    options: {
      A: 'First order',
      B: 'Second order',
      C: 'Third order',
      D: 'Zero order',
    },
    correct_option: 'C',
    explanation: 'Overall order = sum of exponents = 2 + 1 = 3 (Third order).',
  },
  {
    subject: 'Chemistry',
    subsection_id: 3,
    subsection_name: 'Physical Chemistry',
    question_set: 'Set A',
    question_text: 'How does an increase in pressure affect an equilibrium system where the product side contains fewer moles of gaseous molecules than the reactant side?',
    options: {
      A: 'It shifts the equilibrium to the left',
      B: 'It shifts the equilibrium to the right',
      C: 'It has no effect on the equilibrium position',
      D: 'It increases the equilibrium constant (Kc)',
    },
    correct_option: 'B',
    explanation: "Le Chatelier's principle: Increasing pressure shifts equilibrium toward side with fewer gas moles.",
  },
  {
    subject: 'Chemistry',
    subsection_id: 3,
    subsection_name: 'Physical Chemistry',
    question_set: 'Set A',
    question_text: 'What does a negative standard Gibbs free energy change (ΔG°) indicate about a chemical reaction?',
    options: {
      A: 'The reaction is non-spontaneous under standard conditions',
      B: 'The reaction is at equilibrium',
      C: 'The reaction is spontaneous under standard conditions',
      D: 'The reaction is endothermic',
    },
    correct_option: 'C',
    explanation: 'Thermodynamic spontaneity requires ΔG° < 0.',
  },
  {
    subject: 'Chemistry',
    subsection_id: 3,
    subsection_name: 'Physical Chemistry',
    question_set: 'Set A',
    question_text: 'What are the correct SI units for the rate constant (k) of a first-order reaction?',
    options: {
      A: 'M⁻¹ s⁻¹',
      B: 's⁻¹',
      C: 'M s⁻¹',
      D: 'M⁻² s⁻¹',
    },
    correct_option: 'B',
    explanation: 'First order rate constant units: Rate / [A] = (M s⁻¹) / M = s⁻¹.',
  },
  {
    subject: 'Chemistry',
    subsection_id: 3,
    subsection_name: 'Physical Chemistry',
    question_set: 'Set A',
    question_text: 'In an endothermic reaction, what is the correct sign and meaning of the enthalpy change (ΔH)?',
    options: {
      A: 'Negative, heat is released to the surroundings',
      B: 'Positive, heat is absorbed from the surroundings',
      C: 'Zero, no heat is exchanged',
      D: 'Positive, heat is released to the surroundings',
    },
    correct_option: 'B',
    explanation: 'Endothermic processes absorb thermal energy (ΔH > 0).',
  },

  // ORGANIC CHEMISTRY (Subsection 4)
  {
    subject: 'Chemistry',
    subsection_id: 4,
    subsection_name: 'Organic Chemistry',
    question_set: 'Set A',
    question_text: 'What is the general molecular formula for a non-cyclic alkyne with one triple bond?',
    options: {
      A: 'CnH₂n₊₂',
      B: 'CnH₂n',
      C: 'CnH₂n₋₂',
      D: 'CnH₂n₋₄',
    },
    correct_option: 'C',
    explanation: 'Alkynes contain one C≡C triple bond with formula CnH₂n₋₂.',
  },
  {
    subject: 'Chemistry',
    subsection_id: 4,
    subsection_name: 'Organic Chemistry',
    question_set: 'Set A',
    question_text: 'What type of reaction mechanism occurs when ethene reacts with bromine water to form 1,2-dibromoethane?',
    options: {
      A: 'Electrophilic substitution',
      B: 'Nucleophilic addition',
      C: 'Electrophilic addition',
      D: 'Free radical substitution',
    },
    correct_option: 'C',
    explanation: 'Alkene double bonds undergo electrophilic addition with halogen reagents.',
  },
  {
    subject: 'Chemistry',
    subsection_id: 4,
    subsection_name: 'Organic Chemistry',
    question_set: 'Set A',
    question_text: 'What is the final organic product formed when a primary alcohol is strongly refluxed with excess acidified potassium dichromate(VI)?',
    options: {
      A: 'An aldehyde',
      B: 'A ketone',
      C: 'An ester',
      D: 'A carboxylic acid',
    },
    correct_option: 'D',
    explanation: 'Complete oxidation of primary alcohols yields carboxylic acids.',
  },
  {
    subject: 'Chemistry',
    subsection_id: 4,
    subsection_name: 'Organic Chemistry',
    question_set: 'Set A',
    question_text: 'Which of the following alkene molecules can exhibit geometric (cis-trans) isomerism?',
    options: {
      A: '1-butene',
      B: '2-butene',
      C: 'Propene',
      D: '2-methylpropene',
    },
    correct_option: 'B',
    explanation: '2-butene has non-identical groups on each double-bonded carbon atom.',
  },
  {
    subject: 'Chemistry',
    subsection_id: 4,
    subsection_name: 'Organic Chemistry',
    question_set: 'Set A',
    question_text: 'What combination of reagents is required to generate the electrophile (NO₂⁺) for the nitration of benzene?',
    options: {
      A: 'Concentrated HNO₃ and concentrated HCl',
      B: 'Concentrated HNO₃ and concentrated H₂SO₄',
      C: 'Dilute HNO₃ and concentrated H₂SO₄',
      D: 'Concentrated HNO₃ and iron(III) chloride',
    },
    correct_option: 'B',
    explanation: 'Nitrating mixture of conc HNO₃ and conc H₂SO₄ generates nitronium ion NO₂⁺.',
  },

  // RADIOACTIVITY (Subsection 5)
  {
    subject: 'Chemistry',
    subsection_id: 5,
    subsection_name: 'Radioactivity',
    question_set: 'Set A',
    question_text: 'Which type of radioactive emission is identical in mass and charge to a standard helium nucleus?',
    options: {
      A: 'Alpha particle',
      B: 'Beta particle',
      C: 'Gamma ray',
      D: 'Positron',
    },
    correct_option: 'A',
    explanation: 'Alpha particles are ⁴₂He²⁺ helium nuclei.',
  },
  {
    subject: 'Chemistry',
    subsection_id: 5,
    subsection_name: 'Radioactivity',
    question_set: 'Set A',
    question_text: "What fraction of a radioactive isotope's original mass remains undecayed after exactly three half-lives have elapsed?",
    options: {
      A: '1/2',
      B: '1/4',
      C: '1/8',
      D: '1/16',
    },
    correct_option: 'C',
    explanation: 'Fraction remaining = (1/2)³ = 1/8.',
  },
  {
    subject: 'Chemistry',
    subsection_id: 5,
    subsection_name: 'Radioactivity',
    question_set: 'Set A',
    question_text: 'Which type of ionizing radiation possesses the highest penetrating power but the lowest specific ionizing power?',
    options: {
      A: 'Alpha particles',
      B: 'Beta particles',
      C: 'Gamma rays',
      D: 'Neutrons',
    },
    correct_option: 'C',
    explanation: 'Gamma photon radiation is uncharged and deeply penetrating.',
  },
  {
    subject: 'Chemistry',
    subsection_id: 5,
    subsection_name: 'Radioactivity',
    question_set: 'Set A',
    question_text: 'What specific particle is emitted from the nucleus when carbon-14 undergoes radioactive decay to form nitrogen-14?',
    options: {
      A: 'Alpha particle',
      B: 'Beta particle (electron)',
      C: 'Gamma ray',
      D: 'Positron',
    },
    correct_option: 'B',
    explanation: 'Beta-minus decay converts a neutron to a proton, emitting an electron (β⁻ particle).',
  },
  {
    subject: 'Chemistry',
    subsection_id: 5,
    subsection_name: 'Radioactivity',
    question_set: 'Set A',
    question_text: 'In a commercial nuclear fission reactor, what is the primary function of the moderator material like graphite or heavy water?',
    options: {
      A: 'To absorb excess neutrons and stop the reaction',
      B: 'To slow down fast neutrons to sustain the chain reaction',
      C: 'To transport heat away from the reactor core',
      D: 'To provide the primary fissile fuel',
    },
    correct_option: 'B',
    explanation: 'Moderators thermalize (slow down) fission neutrons to increase capture probability.',
  },

  // ==================== CHEMISTRY — SET B ====================
  // BASIC CHEMISTRY (Subsection 1)
  {
    subject: 'Chemistry',
    subsection_id: 1,
    subsection_name: 'Basic Chemistry',
    question_set: 'Set B',
    question_text: 'According to the VSEPR theory, what is the molecular geometry of an ammonia (NH₃) molecule?',
    options: {
      A: 'Tetrahedral',
      B: 'Trigonal planar',
      C: 'Trigonal pyramidal',
      D: 'Bent',
    },
    correct_option: 'C',
    explanation: 'NH₃ has 3 bonding pairs and 1 lone pair, creating a trigonal pyramidal shape.',
  },
  {
    subject: 'Chemistry',
    subsection_id: 1,
    subsection_name: 'Basic Chemistry',
    question_set: 'Set B',
    question_text: 'What volume does 0.25 moles of an ideal gas occupy at standard temperature and pressure (STP)?',
    options: {
      A: '5.6 L',
      B: '11.2 L',
      C: '22.4 L',
      D: '2.8 L',
    },
    correct_option: 'A',
    explanation: 'Volume = 0.25 * 22.4 L = 5.6 L.',
  },
  {
    subject: 'Chemistry',
    subsection_id: 1,
    subsection_name: 'Basic Chemistry',
    question_set: 'Set B',
    question_text: 'What is the molarity of a solution prepared by dissolving 10.0 grams of sodium hydroxide (NaOH) in enough water to make 500 mL of solution?',
    options: {
      A: '0.1 M',
      B: '0.5 M',
      C: '1.0 M',
      D: '2.0 M',
    },
    correct_option: 'B',
    explanation: 'Moles NaOH = 10 / 40 = 0.25 mol. Molarity = 0.25 mol / 0.5 L = 0.5 M.',
  },
  {
    subject: 'Chemistry',
    subsection_id: 1,
    subsection_name: 'Basic Chemistry',
    question_set: 'Set B',
    question_text: 'Which principle states that electrons fill lower-energy atomic orbitals before filling higher-energy ones?',
    options: {
      A: 'Pauli Exclusion Principle',
      B: "Hund's Rule",
      C: 'Aufbau Principle',
      D: 'Heisenberg Uncertainty Principle',
    },
    correct_option: 'C',
    explanation: 'Aufbau principle dictates orbital filling in order of increasing subshell energy.',
  },
  {
    subject: 'Chemistry',
    subsection_id: 1,
    subsection_name: 'Basic Chemistry',
    question_set: 'Set B',
    question_text: 'What is the molar mass of calcium phosphate, Ca₃(PO₄)₂?',
    options: {
      A: '215.2 g/mol',
      B: '279.3 g/mol',
      C: '310.2 g/mol',
      D: '342.1 g/mol',
    },
    correct_option: 'C',
    explanation: 'Molar mass = 3(40.08) + 2(30.97 + 4*16) = 120.24 + 189.94 = 310.18 ≈ 310.2 g/mol.',
  },

  // INORGANIC CHEMISTRY (Subsection 2)
  {
    subject: 'Chemistry',
    subsection_id: 2,
    subsection_name: 'Inorganic Chemistry',
    question_set: 'Set B',
    question_text: 'What is the primary reason the atomic radius decreases as you move from left to right across a period?',
    options: {
      A: 'Added electron shells increase the distance from the nucleus.',
      B: 'Increasing effective nuclear charge pulls the electron cloud closer.',
      C: 'Metallic bonding becomes stronger across the period.',
      D: 'Electron shielding increases significantly.',
    },
    correct_option: 'B',
    explanation: 'Higher effective nuclear charge (Z_eff) exerts stronger electrostatic pull on valence electrons.',
  },
  {
    subject: 'Chemistry',
    subsection_id: 2,
    subsection_name: 'Inorganic Chemistry',
    question_set: 'Set B',
    question_text: 'Which block of the periodic table contains elements that form compounds with variable oxidation states and often act as catalysts?',
    options: {
      A: 's-block',
      B: 'p-block',
      C: 'd-block',
      D: 'f-block',
    },
    correct_option: 'C',
    explanation: 'd-block transition metals feature variable d-orbital oxidation states and catalytic behavior.',
  },
  {
    subject: 'Chemistry',
    subsection_id: 2,
    subsection_name: 'Inorganic Chemistry',
    question_set: 'Set B',
    question_text: 'What gas is released when a dilute acid reacts with a metal carbonate?',
    options: {
      A: 'Hydrogen',
      B: 'Oxygen',
      C: 'Carbon monoxide',
      D: 'Carbon dioxide',
    },
    correct_option: 'D',
    explanation: 'Acid + Carbonate → Salt + Water + Carbon Dioxide (CO₂).',
  },
  {
    subject: 'Chemistry',
    subsection_id: 2,
    subsection_name: 'Inorganic Chemistry',
    question_set: 'Set B',
    question_text: 'According to Lewis acid-base theory, what fundamentally defines a Lewis acid?',
    options: {
      A: 'A proton donor',
      B: 'A proton acceptor',
      C: 'An electron pair donor',
      D: 'An electron pair acceptor',
    },
    correct_option: 'D',
    explanation: 'Lewis acids accept an electron pair.',
  },
  {
    subject: 'Chemistry',
    subsection_id: 2,
    subsection_name: 'Inorganic Chemistry',
    question_set: 'Set B',
    question_text: 'Which alkaline earth metal sulfate is the least soluble in water?',
    options: {
      A: 'Magnesium sulfate',
      B: 'Calcium sulfate',
      C: 'Strontium sulfate',
      D: 'Barium sulfate',
    },
    correct_option: 'D',
    explanation: 'Group 2 sulfate solubility decreases down the group; BaSO₄ is insoluble.',
  },

  // PHYSICAL CHEMISTRY (Subsection 3)
  {
    subject: 'Chemistry',
    subsection_id: 3,
    subsection_name: 'Physical Chemistry',
    question_set: 'Set B',
    question_text: 'How does the continuous addition of a catalyst change the position of equilibrium in a reversible reaction?',
    options: {
      A: 'It shifts equilibrium to the right.',
      B: 'It shifts equilibrium to the left.',
      C: 'It alters the equilibrium constant.',
      D: 'It does not change the position of equilibrium.',
    },
    correct_option: 'D',
    explanation: 'Catalysts speed up forward and reverse rates equally without shifting equilibrium position.',
  },
  {
    subject: 'Chemistry',
    subsection_id: 3,
    subsection_name: 'Physical Chemistry',
    question_set: 'Set B',
    question_text: 'What is the pH of a 0.001 M solution of a strong acid like hydrochloric acid (HCl)?',
    options: {
      A: '1.0',
      B: '2.0',
      C: '3.0',
      D: '4.0',
    },
    correct_option: 'C',
    explanation: 'pH = -log[H+] = -log(10⁻³) = 3.0.',
  },
  {
    subject: 'Chemistry',
    subsection_id: 3,
    subsection_name: 'Physical Chemistry',
    question_set: 'Set B',
    question_text: 'According to the Arrhenius equation, what happens to the rate constant of a reaction when the activation energy is lowered?',
    options: {
      A: 'It decreases.',
      B: 'It increases.',
      C: 'It remains unchanged.',
      D: 'It drops to zero.',
    },
    correct_option: 'B',
    explanation: 'Lowering E_a increases the exponent e^(-E_a/RT), increasing rate constant k.',
  },
  {
    subject: 'Chemistry',
    subsection_id: 3,
    subsection_name: 'Physical Chemistry',
    question_set: 'Set B',
    question_text: 'Which thermodynamic property represents a measure of the degree of disorder or randomness in a chemical system?',
    options: {
      A: 'Enthalpy',
      B: 'Free energy',
      C: 'Entropy',
      D: 'Internal energy',
    },
    correct_option: 'C',
    explanation: 'Entropy (S) measures system microscopic disorder.',
  },
  {
    subject: 'Chemistry',
    subsection_id: 3,
    subsection_name: 'Physical Chemistry',
    question_set: 'Set B',
    question_text: 'What is the defined standard electrode potential (E°) of the standard hydrogen electrode (SHE) at all temperatures?',
    options: {
      A: '-1.00 V',
      B: '0.00 V',
      C: '+1.00 V',
      D: '+2.50 V',
    },
    correct_option: 'B',
    explanation: 'SHE reference potential is defined as 0.00 V.',
  },

  // ORGANIC CHEMISTRY (Subsection 4)
  {
    subject: 'Chemistry',
    subsection_id: 4,
    subsection_name: 'Organic Chemistry',
    question_set: 'Set B',
    question_text: 'What type of reactive intermediate is generated during the homolytic fission of a chlorine molecule (Cl₂) in the presence of UV light?',
    options: {
      A: 'A carbocation',
      B: 'A carbanion',
      C: 'A free radical',
      D: 'An electrophile',
    },
    correct_option: 'C',
    explanation: 'Homolytic cleavage produces chlorine free radicals Cl• with unpaired electrons.',
  },
  {
    subject: 'Chemistry',
    subsection_id: 4,
    subsection_name: 'Organic Chemistry',
    question_set: 'Set B',
    question_text: 'Which functional group is formed during the acid-catalyzed condensation reaction between a carboxylic acid and an alcohol?',
    options: {
      A: 'Ether',
      B: 'Ester',
      C: 'Amide',
      D: 'Anhydride',
    },
    correct_option: 'B',
    explanation: 'Fischer esterification forms an ester functional group (-COO-).',
  },
  {
    subject: 'Chemistry',
    subsection_id: 4,
    subsection_name: 'Organic Chemistry',
    question_set: 'Set B',
    question_text: "According to Markovnikov's rule, what is the major product formed from the addition of hydrogen chloride (HCl) to propene?",
    options: {
      A: '1-chloropropane',
      B: '2-chloropropane',
      C: '1,2-dichloropropane',
      D: '3-chloropropene',
    },
    correct_option: 'B',
    explanation: 'H+ adds to carbon with more hydrogens, placing Cl- on the secondary carbon (2-chloropropane).',
  },
  {
    subject: 'Chemistry',
    subsection_id: 4,
    subsection_name: 'Organic Chemistry',
    question_set: 'Set B',
    question_text: 'Which chemical test yields a "silver mirror" specifically when reacted with an aldehyde but not with a ketone?',
    options: {
      A: "Fehling's solution",
      B: "Benedict's reagent",
      C: "Tollens' reagent",
      D: "Brady's reagent (2,4-DNPH)",
    },
    correct_option: 'C',
    explanation: "Tollens' reagent [Ag(NH₃)₂]+ oxidizes aldehydes to produce a metallic silver mirror.",
  },
  {
    subject: 'Chemistry',
    subsection_id: 4,
    subsection_name: 'Organic Chemistry',
    question_set: 'Set B',
    question_text: 'What classification of polymer is nylon-6,6, which is formed by the reaction of a diamine and a dicarboxylic acid with the elimination of water molecules?',
    options: {
      A: 'Addition polymer',
      B: 'Condensation polymer',
      C: 'Natural polymer',
      D: 'Copolymer',
    },
    correct_option: 'B',
    explanation: 'Nylon-6,6 is synthesized via step-growth condensation polymerization.',
  },

  // RADIOACTIVITY (Subsection 5)
  {
    subject: 'Chemistry',
    subsection_id: 5,
    subsection_name: 'Radioactivity',
    question_set: 'Set B',
    question_text: 'How does the atomic number of a parent element change when its nucleus successfully undergoes alpha decay?',
    options: {
      A: 'It increases by 1',
      B: 'It decreases by 1',
      C: 'It decreases by 2',
      D: 'It decreases by 4',
    },
    correct_option: 'C',
    explanation: 'Alpha emission removes 2 protons and 2 neutrons; atomic number Z decreases by 2.',
  },
  {
    subject: 'Chemistry',
    subsection_id: 5,
    subsection_name: 'Radioactivity',
    question_set: 'Set B',
    question_text: 'Which physical unit is traditionally used to measure the biological dose equivalent of absorbed ionizing radiation in human tissue?',
    options: {
      A: 'Becquerel (Bq)',
      B: 'Gray (Gy)',
      C: 'Sievert (Sv)',
      D: 'Curie (Ci)',
    },
    correct_option: 'C',
    explanation: 'The Sievert (Sv) measures biological radiation equivalent dose.',
  },
  {
    subject: 'Chemistry',
    subsection_id: 5,
    subsection_name: 'Radioactivity',
    question_set: 'Set B',
    question_text: 'In the nuclear fission of Uranium-235, if it absorbs a neutron and splits into Barium-141 and Krypton-92, how many independent neutrons are released?',
    options: {
      A: '1',
      B: '2',
      C: '3',
      D: '4',
    },
    correct_option: 'C',
    explanation: 'Mass balance: 235 + 1 = 141 + 92 + 3(1) = 236. Three neutrons are released.',
  },
  {
    subject: 'Chemistry',
    subsection_id: 5,
    subsection_name: 'Radioactivity',
    question_set: 'Set B',
    question_text: 'What scientific term is used to describe the time required for the activity of a specific radioactive sample to fall to exactly half of its original measured value?',
    options: {
      A: 'Decay constant',
      B: 'Half-life',
      C: 'Mean life',
      D: 'Activity duration',
    },
    correct_option: 'B',
    explanation: 'Half-life t_1/2 is the duration for 50% radionuclide decay.',
  },
  {
    subject: 'Chemistry',
    subsection_id: 5,
    subsection_name: 'Radioactivity',
    question_set: 'Set B',
    question_text: 'How does the pure emission of a gamma ray affect the mass number and atomic number of an unstable atomic nucleus?',
    options: {
      A: 'Mass number decreases by 1, atomic number decreases by 1',
      B: 'Mass number remains unchanged, atomic number increases by 1',
      C: 'Mass number remains unchanged, atomic number remains unchanged',
      D: 'Mass number decreases by 4, atomic number decreases by 2',
    },
    correct_option: 'C',
    explanation: 'Gamma emission releases excess nuclear energy without altering nucleon counts (A and Z unchanged).',
  },
]

const seedDatabase = async () => {
  try {
    const mongoUri = process.env.MONGODB_URI || 'mongodb://localhost:27017/studyhub'
    await mongoose.connect(mongoUri)
    console.log('Connected to MongoDB...')

    await CbtQuestion.deleteMany({})
    console.log('Cleared existing CBT questions.')

    const created = await CbtQuestion.insertMany(questionsData)
    console.log(`Successfully seeded ${created.length} CBT questions into MongoDB!`)

    process.exit(0)
  } catch (error) {
    console.error('Error seeding CBT questions:', error)
    process.exit(1)
  }
}

seedDatabase()
